/*
 * generated by Xtext
 */
package br.usp.icmc.amenu.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the IDE.
 */
public class AMenuUiModule extends br.usp.icmc.amenu.ui.AbstractAMenuUiModule {
	public AMenuUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
