/*
* generated by Xtext
*/
package br.usp.icmc.amenu.ui.contentassist.antlr;

import java.util.Collection;
import java.util.Map;
import java.util.HashMap;

import org.antlr.runtime.RecognitionException;
import org.eclipse.xtext.AbstractElement;
import org.eclipse.xtext.ui.editor.contentassist.antlr.AbstractContentAssistParser;
import org.eclipse.xtext.ui.editor.contentassist.antlr.FollowElement;
import org.eclipse.xtext.ui.editor.contentassist.antlr.internal.AbstractInternalContentAssistParser;

import com.google.inject.Inject;

import br.usp.icmc.amenu.services.AMenuGrammarAccess;

public class AMenuParser extends AbstractContentAssistParser {
	
	@Inject
	private AMenuGrammarAccess grammarAccess;
	
	private Map<AbstractElement, String> nameMappings;
	
	@Override
	protected br.usp.icmc.amenu.ui.contentassist.antlr.internal.InternalAMenuParser createParser() {
		br.usp.icmc.amenu.ui.contentassist.antlr.internal.InternalAMenuParser result = new br.usp.icmc.amenu.ui.contentassist.antlr.internal.InternalAMenuParser(null);
		result.setGrammarAccess(grammarAccess);
		return result;
	}
	
	@Override
	protected String getRuleName(AbstractElement element) {
		if (nameMappings == null) {
			nameMappings = new HashMap<AbstractElement, String>() {
				private static final long serialVersionUID = 1L;
				{
					put(grammarAccess.getConfigurationsAccess().getAlternatives_0(), "rule__Configurations__Alternatives_0");
					put(grammarAccess.getConfigurationsAccess().getAlternatives_1(), "rule__Configurations__Alternatives_1");
					put(grammarAccess.getTypeAccess().getAlternatives(), "rule__Type__Alternatives");
					put(grammarAccess.getStyleAccess().getAlternatives(), "rule__Style__Alternatives");
					put(grammarAccess.getPositionAccess().getAlternatives(), "rule__Position__Alternatives");
					put(grammarAccess.getDirectionAccess().getAlternatives(), "rule__Direction__Alternatives");
					put(grammarAccess.getTargetAccess().getAlternatives(), "rule__Target__Alternatives");
					put(grammarAccess.getMenuAccess().getGroup_0(), "rule__Menu__Group_0__0");
					put(grammarAccess.getMenuAccess().getGroup_1(), "rule__Menu__Group_1__0");
					put(grammarAccess.getMenuAccess().getGroup_2(), "rule__Menu__Group_2__0");
					put(grammarAccess.getMenuAccess().getGroup_3(), "rule__Menu__Group_3__0");
					put(grammarAccess.getMenuAccess().getGroup_4(), "rule__Menu__Group_4__0");
					put(grammarAccess.getMenuAccess().getGroup_5(), "rule__Menu__Group_5__0");
					put(grammarAccess.getMenuAccess().getGroup_6(), "rule__Menu__Group_6__0");
					put(grammarAccess.getMenuAccess().getGroup_6_4(), "rule__Menu__Group_6_4__0");
					put(grammarAccess.getConfigurationsAccess().getGroup(), "rule__Configurations__Group__0");
					put(grammarAccess.getConfigurationsAccess().getGroup_0_0(), "rule__Configurations__Group_0_0__0");
					put(grammarAccess.getConfigurationsAccess().getGroup_0_1(), "rule__Configurations__Group_0_1__0");
					put(grammarAccess.getConfigurationsAccess().getGroup_1_0(), "rule__Configurations__Group_1_0__0");
					put(grammarAccess.getConfigurationsAccess().getGroup_1_1(), "rule__Configurations__Group_1_1__0");
					put(grammarAccess.getConfigAccess().getGroup(), "rule__Config__Group__0");
					put(grammarAccess.getItemAccess().getGroup(), "rule__Item__Group__0");
					put(grammarAccess.getItemAccess().getGroup_1_0(), "rule__Item__Group_1_0__0");
					put(grammarAccess.getItemAccess().getGroup_1_1(), "rule__Item__Group_1_1__0");
					put(grammarAccess.getItemAccess().getGroup_1_2(), "rule__Item__Group_1_2__0");
					put(grammarAccess.getItemAccess().getGroup_1_3(), "rule__Item__Group_1_3__0");
					put(grammarAccess.getItemAccess().getGroup_1_4(), "rule__Item__Group_1_4__0");
					put(grammarAccess.getItemAccess().getGroup_1_5(), "rule__Item__Group_1_5__0");
					put(grammarAccess.getItemAccess().getGroup_1_6(), "rule__Item__Group_1_6__0");
					put(grammarAccess.getItemAccess().getGroup_1_7(), "rule__Item__Group_1_7__0");
					put(grammarAccess.getItemAccess().getGroup_1_8(), "rule__Item__Group_1_8__0");
					put(grammarAccess.getSubMenuAccess().getGroup(), "rule__SubMenu__Group__0");
					put(grammarAccess.getSubMenuAccess().getGroup_1_0(), "rule__SubMenu__Group_1_0__0");
					put(grammarAccess.getSubMenuAccess().getGroup_1_1(), "rule__SubMenu__Group_1_1__0");
					put(grammarAccess.getSubMenuAccess().getGroup_1_1_3(), "rule__SubMenu__Group_1_1_3__0");
					put(grammarAccess.getSubMenuAccess().getGroup_1_1_3_1(), "rule__SubMenu__Group_1_1_3_1__0");
					put(grammarAccess.getIconAccess().getGroup(), "rule__Icon__Group__0");
					put(grammarAccess.getIconAccess().getGroup_1_0(), "rule__Icon__Group_1_0__0");
					put(grammarAccess.getIconAccess().getGroup_1_1(), "rule__Icon__Group_1_1__0");
					put(grammarAccess.getIconAccess().getGroup_1_2(), "rule__Icon__Group_1_2__0");
					put(grammarAccess.getIconAccess().getGroup_1_3(), "rule__Icon__Group_1_3__0");
					put(grammarAccess.getIconAccess().getGroup_1_4(), "rule__Icon__Group_1_4__0");
					put(grammarAccess.getMenuAccess().getNameAssignment_0_2(), "rule__Menu__NameAssignment_0_2");
					put(grammarAccess.getMenuAccess().getTypeAssignment_1_2(), "rule__Menu__TypeAssignment_1_2");
					put(grammarAccess.getMenuAccess().getStyleAssignment_2_2(), "rule__Menu__StyleAssignment_2_2");
					put(grammarAccess.getMenuAccess().getPositionAssignment_3_2(), "rule__Menu__PositionAssignment_3_2");
					put(grammarAccess.getMenuAccess().getDecoratorAssignment_4_2(), "rule__Menu__DecoratorAssignment_4_2");
					put(grammarAccess.getMenuAccess().getConfigurationAssignment_5_3(), "rule__Menu__ConfigurationAssignment_5_3");
					put(grammarAccess.getMenuAccess().getItemsAssignment_6_3(), "rule__Menu__ItemsAssignment_6_3");
					put(grammarAccess.getMenuAccess().getItemsAssignment_6_4_1(), "rule__Menu__ItemsAssignment_6_4_1");
					put(grammarAccess.getConfigurationsAccess().getConfig_topAssignment_0_0_1(), "rule__Configurations__Config_topAssignment_0_0_1");
					put(grammarAccess.getConfigurationsAccess().getConfig_childrenAssignment_0_1_1(), "rule__Configurations__Config_childrenAssignment_0_1_1");
					put(grammarAccess.getConfigurationsAccess().getConfig_topAssignment_1_0_2(), "rule__Configurations__Config_topAssignment_1_0_2");
					put(grammarAccess.getConfigurationsAccess().getConfig_childrenAssignment_1_1_2(), "rule__Configurations__Config_childrenAssignment_1_1_2");
					put(grammarAccess.getConfigAccess().getFeatureAssignment_1(), "rule__Config__FeatureAssignment_1");
					put(grammarAccess.getConfigAccess().getColorAssignment_3(), "rule__Config__ColorAssignment_3");
					put(grammarAccess.getItemAccess().getNameAssignment_1_0_2(), "rule__Item__NameAssignment_1_0_2");
					put(grammarAccess.getItemAccess().getDecoratorAssignment_1_1_2(), "rule__Item__DecoratorAssignment_1_1_2");
					put(grammarAccess.getItemAccess().getActionAssignment_1_2_2(), "rule__Item__ActionAssignment_1_2_2");
					put(grammarAccess.getItemAccess().getLabelAssignment_1_3_2(), "rule__Item__LabelAssignment_1_3_2");
					put(grammarAccess.getItemAccess().getTitleAssignment_1_4_2(), "rule__Item__TitleAssignment_1_4_2");
					put(grammarAccess.getItemAccess().getDirectionAssignment_1_5_2(), "rule__Item__DirectionAssignment_1_5_2");
					put(grammarAccess.getItemAccess().getTargetAssignment_1_6_2(), "rule__Item__TargetAssignment_1_6_2");
					put(grammarAccess.getItemAccess().getIconAssignment_1_7_2(), "rule__Item__IconAssignment_1_7_2");
					put(grammarAccess.getItemAccess().getSubmenuAssignment_1_8_2(), "rule__Item__SubmenuAssignment_1_8_2");
					put(grammarAccess.getSubMenuAccess().getDecoratorAssignment_1_0_2(), "rule__SubMenu__DecoratorAssignment_1_0_2");
					put(grammarAccess.getSubMenuAccess().getItemsAssignment_1_1_3_0(), "rule__SubMenu__ItemsAssignment_1_1_3_0");
					put(grammarAccess.getSubMenuAccess().getItemsAssignment_1_1_3_1_1(), "rule__SubMenu__ItemsAssignment_1_1_3_1_1");
					put(grammarAccess.getIconAccess().getNameAssignment_1_0_2(), "rule__Icon__NameAssignment_1_0_2");
					put(grammarAccess.getIconAccess().getPositionAssignment_1_1_2(), "rule__Icon__PositionAssignment_1_1_2");
					put(grammarAccess.getIconAccess().getDecoratorAssignment_1_2_2(), "rule__Icon__DecoratorAssignment_1_2_2");
					put(grammarAccess.getIconAccess().getText_altAssignment_1_3_2(), "rule__Icon__Text_altAssignment_1_3_2");
					put(grammarAccess.getIconAccess().getAddressAssignment_1_4_2(), "rule__Icon__AddressAssignment_1_4_2");
					put(grammarAccess.getMenuAccess().getUnorderedGroup(), "rule__Menu__UnorderedGroup");
					put(grammarAccess.getItemAccess().getUnorderedGroup_1(), "rule__Item__UnorderedGroup_1");
					put(grammarAccess.getSubMenuAccess().getUnorderedGroup_1(), "rule__SubMenu__UnorderedGroup_1");
					put(grammarAccess.getIconAccess().getUnorderedGroup_1(), "rule__Icon__UnorderedGroup_1");
				}
			};
		}
		return nameMappings.get(element);
	}
	
	@Override
	protected Collection<FollowElement> getFollowElements(AbstractInternalContentAssistParser parser) {
		try {
			br.usp.icmc.amenu.ui.contentassist.antlr.internal.InternalAMenuParser typedParser = (br.usp.icmc.amenu.ui.contentassist.antlr.internal.InternalAMenuParser) parser;
			typedParser.entryRuleMenu();
			return typedParser.getFollowElements();
		} catch(RecognitionException ex) {
			throw new RuntimeException(ex);
		}		
	}
	
	@Override
	protected String[] getInitialHiddenTokens() {
		return new String[] { "RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT" };
	}
	
	public AMenuGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}
	
	public void setGrammarAccess(AMenuGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
