/*
* generated by Xtext
*/
package br.usp.icmc.amenu.parser.antlr;

import com.google.inject.Inject;

import org.eclipse.xtext.parser.antlr.XtextTokenStream;
import br.usp.icmc.amenu.services.AMenuGrammarAccess;

public class AMenuParser extends org.eclipse.xtext.parser.antlr.AbstractAntlrParser {
	
	@Inject
	private AMenuGrammarAccess grammarAccess;
	
	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	
	@Override
	protected br.usp.icmc.amenu.parser.antlr.internal.InternalAMenuParser createParser(XtextTokenStream stream) {
		return new br.usp.icmc.amenu.parser.antlr.internal.InternalAMenuParser(stream, getGrammarAccess());
	}
	
	@Override 
	protected String getDefaultRuleName() {
		return "Menu";
	}
	
	public AMenuGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}
	
	public void setGrammarAccess(AMenuGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
	
}
