package br.usp.icmc.amenu.generator;

import br.usp.icmc.amenu.aMenu.Menu;
import br.usp.icmc.amenu.generator.MenuAbstract;
import org.eclipse.xtend2.lib.StringConcatenation;

@SuppressWarnings("all")
public class Dropdown extends MenuAbstract {
  public Dropdown(final Menu menu) {
    super(menu);
  }
  
  public CharSequence genJavascript() {
    StringConcatenation _builder = new StringConcatenation();
    _builder.append("<script src=\"http://code.jquery.com/jquery-1.11.0.min.js\"></script>");
    _builder.newLine();
    _builder.append("<script src=\"http://agua.intermidia.icmc.usp.br:8080/ameg/plugins/dropdown.js\"></script>");
    _builder.newLine();
    _builder.append("<script>");
    _builder.newLine();
    _builder.append("    ");
    _builder.append("$(document).ready(function() {");
    _builder.newLine();
    _builder.append("        ");
    _builder.append("$(\"#");
    String _idMenu = this.getIdMenu();
    _builder.append(_idMenu, "        ");
    _builder.append("\").accessibleMenu();");
    _builder.newLineIfNotEmpty();
    _builder.append("    ");
    _builder.append("});");
    _builder.newLine();
    _builder.append("</script>");
    _builder.newLine();
    return _builder;
  }
  
  protected CharSequence _colorSimple() {
    StringConcatenation _builder = new StringConcatenation();
    _builder.append("<style type=\"text/css\">");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("#");
    String _idMenu = this.getIdMenu();
    _builder.append(_idMenu, "\t");
    _builder.append(",");
    _builder.newLineIfNotEmpty();
    _builder.append("\t");
    _builder.append("#");
    String _idMenu_1 = this.getIdMenu();
    _builder.append(_idMenu_1, "\t");
    _builder.append(" ul,");
    _builder.newLineIfNotEmpty();
    _builder.append("\t");
    _builder.append("#");
    String _idMenu_2 = this.getIdMenu();
    _builder.append(_idMenu_2, "\t");
    _builder.append(" ul li,");
    _builder.newLineIfNotEmpty();
    _builder.append("\t");
    _builder.append("#");
    String _idMenu_3 = this.getIdMenu();
    _builder.append(_idMenu_3, "\t");
    _builder.append(" ul li a,");
    _builder.newLineIfNotEmpty();
    _builder.append("\t");
    _builder.append("#");
    String _idMenu_4 = this.getIdMenu();
    _builder.append(_idMenu_4, "\t");
    _builder.append(" ul li span {");
    _builder.newLineIfNotEmpty();
    _builder.append("\t  ");
    _builder.append("margin: 0;");
    _builder.newLine();
    _builder.append("\t  ");
    _builder.append("padding: 0;");
    _builder.newLine();
    _builder.append("\t  ");
    _builder.append("border: 0;");
    _builder.newLine();
    _builder.append("\t  ");
    _builder.append("list-style: none;");
    _builder.newLine();
    _builder.append("\t  ");
    _builder.append("line-height: 1;");
    _builder.newLine();
    _builder.append("\t  ");
    _builder.append("display: block;");
    _builder.newLine();
    _builder.append("\t  ");
    _builder.append("position: relative;");
    _builder.newLine();
    _builder.append("\t  ");
    _builder.append("-webkit-box-sizing: border-box;");
    _builder.newLine();
    _builder.append("\t  ");
    _builder.append("-moz-box-sizing: border-box;");
    _builder.newLine();
    _builder.append("\t  ");
    _builder.append("box-sizing: border-box;");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("}");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("#");
    String _idMenu_5 = this.getIdMenu();
    _builder.append(_idMenu_5, "\t");
    _builder.append(" {");
    _builder.newLineIfNotEmpty();
    _builder.append("\t  ");
    _builder.append("width: 100%;");
    _builder.newLine();
    _builder.append("\t  ");
    _builder.append("background: ");
    String _top = this._color.getTop("background");
    _builder.append(_top, "\t  ");
    _builder.append(";");
    _builder.newLineIfNotEmpty();
    _builder.append("\t  ");
    _builder.append("display: inline-block;");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("}");
    _builder.newLine();
    _builder.append("\t");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("#");
    String _idMenu_6 = this.getIdMenu();
    _builder.append(_idMenu_6, "\t");
    _builder.append(" > ul > li {");
    _builder.newLineIfNotEmpty();
    _builder.append("\t  ");
    _builder.append("float: left;");
    _builder.newLine();
    _builder.append("\t  ");
    _builder.append("display: inline-block;");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("}");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("#");
    String _idMenu_7 = this.getIdMenu();
    _builder.append(_idMenu_7, "\t");
    _builder.append(" > ul > li > a ,");
    _builder.newLineIfNotEmpty();
    _builder.append("\t");
    _builder.append("#");
    String _idMenu_8 = this.getIdMenu();
    _builder.append(_idMenu_8, "\t");
    _builder.append(" > ul > li > span {");
    _builder.newLineIfNotEmpty();
    _builder.append("\t  ");
    _builder.append("padding: 10px 25px 13px 25px;");
    _builder.newLine();
    _builder.append("\t  ");
    _builder.append("border-top: 2px solid ");
    String _top_1 = this._color.getTop("border");
    _builder.append(_top_1, "\t  ");
    _builder.append(";");
    _builder.newLineIfNotEmpty();
    _builder.append("\t  ");
    _builder.append("border-bottom: 2px solid ");
    String _top_2 = this._color.getTop("border");
    _builder.append(_top_2, "\t  ");
    _builder.append(";");
    _builder.newLineIfNotEmpty();
    _builder.append("\t  ");
    _builder.append("border-right: 2px solid ");
    String _top_3 = this._color.getTop("border");
    _builder.append(_top_3, "\t  ");
    _builder.append(";");
    _builder.newLineIfNotEmpty();
    _builder.append("\t  ");
    _builder.append("text-decoration: none;");
    _builder.newLine();
    _builder.append("\t  ");
    _builder.append("color: ");
    String _top_4 = this._color.getTop("color");
    _builder.append(_top_4, "\t  ");
    _builder.append(";");
    _builder.newLineIfNotEmpty();
    _builder.append("\t  ");
    _builder.append("cursor:pointer;");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("}");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("#");
    String _idMenu_9 = this.getIdMenu();
    _builder.append(_idMenu_9, "\t");
    _builder.append(" > ul > li:first-child > a ,");
    _builder.newLineIfNotEmpty();
    _builder.append("\t");
    _builder.append("#");
    String _idMenu_10 = this.getIdMenu();
    _builder.append(_idMenu_10, "\t");
    _builder.append(" > ul > li:first-child > span {");
    _builder.newLineIfNotEmpty();
    _builder.append("\t  ");
    _builder.append("border-left: 2px solid ");
    String _top_5 = this._color.getTop("border");
    _builder.append(_top_5, "\t  ");
    _builder.append(";");
    _builder.newLineIfNotEmpty();
    _builder.append("\t");
    _builder.append("}");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("#");
    String _idMenu_11 = this.getIdMenu();
    _builder.append(_idMenu_11, "\t");
    _builder.append(" > ul > li.open > a,");
    _builder.newLineIfNotEmpty();
    _builder.append("\t");
    _builder.append("#");
    String _idMenu_12 = this.getIdMenu();
    _builder.append(_idMenu_12, "\t");
    _builder.append(" > ul > li.focus > a,");
    _builder.newLineIfNotEmpty();
    _builder.append("\t");
    _builder.append("#");
    String _idMenu_13 = this.getIdMenu();
    _builder.append(_idMenu_13, "\t");
    _builder.append(" > ul > li:hover > a,");
    _builder.newLineIfNotEmpty();
    _builder.append("\t");
    _builder.append("#");
    String _idMenu_14 = this.getIdMenu();
    _builder.append(_idMenu_14, "\t");
    _builder.append(" > ul > li > a:hover,");
    _builder.newLineIfNotEmpty();
    _builder.append("\t");
    _builder.append("#");
    String _idMenu_15 = this.getIdMenu();
    _builder.append(_idMenu_15, "\t");
    _builder.append(" > ul > li.active > a,");
    _builder.newLineIfNotEmpty();
    _builder.append("\t");
    _builder.append("#");
    String _idMenu_16 = this.getIdMenu();
    _builder.append(_idMenu_16, "\t");
    _builder.append(" > ul > li.open > span,");
    _builder.newLineIfNotEmpty();
    _builder.append("\t");
    _builder.append("#");
    String _idMenu_17 = this.getIdMenu();
    _builder.append(_idMenu_17, "\t");
    _builder.append(" > ul > li.focus > span,");
    _builder.newLineIfNotEmpty();
    _builder.append("\t");
    _builder.append("#");
    String _idMenu_18 = this.getIdMenu();
    _builder.append(_idMenu_18, "\t");
    _builder.append(" > ul > li:hover > span,");
    _builder.newLineIfNotEmpty();
    _builder.append("\t");
    _builder.append("#");
    String _idMenu_19 = this.getIdMenu();
    _builder.append(_idMenu_19, "\t");
    _builder.append(" > ul > li > span:hover,");
    _builder.newLineIfNotEmpty();
    _builder.append("\t");
    _builder.append("#");
    String _idMenu_20 = this.getIdMenu();
    _builder.append(_idMenu_20, "\t");
    _builder.append(" > ul > li.active > span {");
    _builder.newLineIfNotEmpty();
    _builder.append("\t  ");
    _builder.append("color: ");
    String _top_6 = this._color.getTop("color-hover");
    _builder.append(_top_6, "\t  ");
    _builder.append(";");
    _builder.newLineIfNotEmpty();
    _builder.append("\t  ");
    _builder.append("background: ");
    String _top_7 = this._color.getTop("background-hover");
    _builder.append(_top_7, "\t  ");
    _builder.append(";");
    _builder.newLineIfNotEmpty();
    _builder.append("\t");
    _builder.append("}");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("#");
    String _idMenu_21 = this.getIdMenu();
    _builder.append(_idMenu_21, "\t");
    _builder.append(" > ul > li.has-sub > a,");
    _builder.newLineIfNotEmpty();
    _builder.append("\t");
    _builder.append("#");
    String _idMenu_22 = this.getIdMenu();
    _builder.append(_idMenu_22, "\t");
    _builder.append(" > ul > li.has-sub > span {");
    _builder.newLineIfNotEmpty();
    _builder.append("\t  ");
    _builder.append("padding-right: 45px;");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("}");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("#");
    String _idMenu_23 = this.getIdMenu();
    _builder.append(_idMenu_23, "\t");
    _builder.append(" > ul > li.has-sub::after {");
    _builder.newLineIfNotEmpty();
    _builder.append("\t  ");
    _builder.append("content: \"\";");
    _builder.newLine();
    _builder.append("\t  ");
    _builder.append("position: absolute;");
    _builder.newLine();
    _builder.append("\t  ");
    _builder.append("right: 15px;");
    _builder.newLine();
    _builder.append("\t  ");
    _builder.append("top: 13px;");
    _builder.newLine();
    _builder.append("\t  ");
    _builder.append("width: 8px;");
    _builder.newLine();
    _builder.append("\t  ");
    _builder.append("height: 8px;");
    _builder.newLine();
    _builder.append("\t  ");
    _builder.append("border-bottom: 2px solid ");
    String _top_8 = this._color.getTop("color");
    _builder.append(_top_8, "\t  ");
    _builder.append(";");
    _builder.newLineIfNotEmpty();
    _builder.append("\t  ");
    _builder.append("border-right: 2px solid ");
    String _top_9 = this._color.getTop("color");
    _builder.append(_top_9, "\t  ");
    _builder.append(";");
    _builder.newLineIfNotEmpty();
    _builder.append("\t  ");
    _builder.append("content: \"\";");
    _builder.newLine();
    _builder.append("\t  ");
    _builder.append("-webkit-transform: rotate(45deg);");
    _builder.newLine();
    _builder.append("\t  ");
    _builder.append("-moz-transform: rotate(45deg);");
    _builder.newLine();
    _builder.append("\t  ");
    _builder.append("-ms-transform: rotate(45deg);");
    _builder.newLine();
    _builder.append("\t  ");
    _builder.append("-o-transform: rotate(45deg);");
    _builder.newLine();
    _builder.append("\t  ");
    _builder.append("transform: rotate(45deg);");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("}");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("#");
    String _idMenu_24 = this.getIdMenu();
    _builder.append(_idMenu_24, "\t");
    _builder.append(" > ul > li.has-sub.focus::after,");
    _builder.newLineIfNotEmpty();
    _builder.append("\t");
    _builder.append("#");
    String _idMenu_25 = this.getIdMenu();
    _builder.append(_idMenu_25, "\t");
    _builder.append(" > ul > li.has-sub:hover::after,");
    _builder.newLineIfNotEmpty();
    _builder.append("\t");
    _builder.append("#");
    String _idMenu_26 = this.getIdMenu();
    _builder.append(_idMenu_26, "\t");
    _builder.append(" > ul > li.has-sub.active::after,");
    _builder.newLineIfNotEmpty();
    _builder.append("\t");
    _builder.append("#");
    String _idMenu_27 = this.getIdMenu();
    _builder.append(_idMenu_27, "\t");
    _builder.append(" > ul > li.has-sub.open::after{");
    _builder.newLineIfNotEmpty();
    _builder.append("\t  ");
    _builder.append("border-bottom-color: ");
    String _top_10 = this._color.getTop("color-hover");
    _builder.append(_top_10, "\t  ");
    _builder.append(";");
    _builder.newLineIfNotEmpty();
    _builder.append("\t  ");
    _builder.append("border-right-color: ");
    String _top_11 = this._color.getTop("color-hover");
    _builder.append(_top_11, "\t  ");
    _builder.append(";");
    _builder.newLineIfNotEmpty();
    _builder.append("\t");
    _builder.append("}");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("#");
    String _idMenu_28 = this.getIdMenu();
    _builder.append(_idMenu_28, "\t");
    _builder.append(" ul ul {");
    _builder.newLineIfNotEmpty();
    _builder.append("\t  ");
    _builder.append("position: absolute;");
    _builder.newLine();
    _builder.append("\t  ");
    _builder.append("left: -9999px;");
    _builder.newLine();
    _builder.append("\t  ");
    _builder.append("top: 60px;");
    _builder.newLine();
    _builder.append("\t  ");
    _builder.append("font-size: 13px;");
    _builder.newLine();
    _builder.append("\t  ");
    _builder.append("opacity: 0;");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("}");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("#");
    String _idMenu_29 = this.getIdMenu();
    _builder.append(_idMenu_29, "\t");
    _builder.append(" > ul > li > ul {");
    _builder.newLineIfNotEmpty();
    _builder.append("\t  ");
    _builder.append("top: 120px;");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("}");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("#");
    String _idMenu_30 = this.getIdMenu();
    _builder.append(_idMenu_30, "\t");
    _builder.append(" > ul > li.open > ul {");
    _builder.newLineIfNotEmpty();
    _builder.append("\t  ");
    _builder.append("top: 100%;");
    _builder.newLine();
    _builder.append("\t  ");
    _builder.append("left: 0;");
    _builder.newLine();
    _builder.append("\t  ");
    _builder.append("opacity: 1;");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("}");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("#");
    String _idMenu_31 = this.getIdMenu();
    _builder.append(_idMenu_31, "\t");
    _builder.append(" ul ul ul {");
    _builder.newLineIfNotEmpty();
    _builder.append("\t  ");
    _builder.append("margin-left: -1px;");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("z-index: 1;");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("}");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("#");
    String _idMenu_32 = this.getIdMenu();
    _builder.append(_idMenu_32, "\t");
    _builder.append(" ul ul > li.open > ul {");
    _builder.newLineIfNotEmpty();
    _builder.append("\t  ");
    _builder.append("display:block;");
    _builder.newLine();
    _builder.append("\t  ");
    _builder.append("left: 100%;");
    _builder.newLine();
    _builder.append("\t  ");
    _builder.append("top: 0;");
    _builder.newLine();
    _builder.append("\t  ");
    _builder.append("opacity: 1;");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("}");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("#");
    String _idMenu_33 = this.getIdMenu();
    _builder.append(_idMenu_33, "\t");
    _builder.append(" ul ul li a,");
    _builder.newLineIfNotEmpty();
    _builder.append("\t");
    _builder.append("#");
    String _idMenu_34 = this.getIdMenu();
    _builder.append(_idMenu_34, "\t");
    _builder.append(" ul ul li span {");
    _builder.newLineIfNotEmpty();
    _builder.append("\t  ");
    _builder.append("text-decoration: none;");
    _builder.newLine();
    _builder.append("\t  ");
    _builder.append("padding: 11px 25px;");
    _builder.newLine();
    _builder.append("\t  ");
    _builder.append("width: 180px;");
    _builder.newLine();
    _builder.append("\t  ");
    _builder.append("color: ");
    String _children = this._color.getChildren("color");
    _builder.append(_children, "\t  ");
    _builder.append(";");
    _builder.newLineIfNotEmpty();
    _builder.append("\t  ");
    _builder.append("background: ");
    String _children_1 = this._color.getChildren("background");
    _builder.append(_children_1, "\t  ");
    _builder.append(";");
    _builder.newLineIfNotEmpty();
    _builder.append("\t  ");
    _builder.append("border-left: 1px solid ");
    String _children_2 = this._color.getChildren("border");
    _builder.append(_children_2, "\t  ");
    _builder.append(";");
    _builder.newLineIfNotEmpty();
    _builder.append("\t  ");
    _builder.append("border-right: 1px solid ");
    String _children_3 = this._color.getChildren("border");
    _builder.append(_children_3, "\t  ");
    _builder.append(";");
    _builder.newLineIfNotEmpty();
    _builder.append("\t  ");
    _builder.append("border-top: 1px solid ");
    String _children_4 = this._color.getChildren("border");
    _builder.append(_children_4, "\t  ");
    _builder.append(";");
    _builder.newLineIfNotEmpty();
    _builder.append("\t  ");
    _builder.append("cursor:pointer;");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("}");
    _builder.newLine();
    _builder.append("\t");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("#");
    String _idMenu_35 = this.getIdMenu();
    _builder.append(_idMenu_35, "\t");
    _builder.append(" ul ul li.open > a,");
    _builder.newLineIfNotEmpty();
    _builder.append("\t");
    _builder.append("#");
    String _idMenu_36 = this.getIdMenu();
    _builder.append(_idMenu_36, "\t");
    _builder.append(" ul ul li.focus > a,");
    _builder.newLineIfNotEmpty();
    _builder.append("\t");
    _builder.append("#");
    String _idMenu_37 = this.getIdMenu();
    _builder.append(_idMenu_37, "\t");
    _builder.append(" ul ul li:hover > a,");
    _builder.newLineIfNotEmpty();
    _builder.append("\t");
    _builder.append("#");
    String _idMenu_38 = this.getIdMenu();
    _builder.append(_idMenu_38, "\t");
    _builder.append(" ul ul li.active > a,");
    _builder.newLineIfNotEmpty();
    _builder.append("\t");
    _builder.append("#");
    String _idMenu_39 = this.getIdMenu();
    _builder.append(_idMenu_39, "\t");
    _builder.append(" ul ul li.open > span,");
    _builder.newLineIfNotEmpty();
    _builder.append("\t");
    _builder.append("#");
    String _idMenu_40 = this.getIdMenu();
    _builder.append(_idMenu_40, "\t");
    _builder.append(" ul ul li.focus > span,");
    _builder.newLineIfNotEmpty();
    _builder.append("\t");
    _builder.append("#");
    String _idMenu_41 = this.getIdMenu();
    _builder.append(_idMenu_41, "\t");
    _builder.append(" ul ul li:hover > span,");
    _builder.newLineIfNotEmpty();
    _builder.append("\t");
    _builder.append("#");
    String _idMenu_42 = this.getIdMenu();
    _builder.append(_idMenu_42, "\t");
    _builder.append(" ul ul li.active > span {");
    _builder.newLineIfNotEmpty();
    _builder.append("\t  ");
    _builder.append("color: ");
    String _children_5 = this._color.getChildren("color-hover");
    _builder.append(_children_5, "\t  ");
    _builder.append(";");
    _builder.newLineIfNotEmpty();
    _builder.append("\t  ");
    _builder.append("background:");
    String _children_6 = this._color.getChildren("background-hover");
    _builder.append(_children_6, "\t  ");
    _builder.append(";");
    _builder.newLineIfNotEmpty();
    _builder.append("\t");
    _builder.append("}");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("#");
    String _idMenu_43 = this.getIdMenu();
    _builder.append(_idMenu_43, "\t");
    _builder.append(" ul ul li:last-child > a,");
    _builder.newLineIfNotEmpty();
    _builder.append("\t");
    _builder.append("#");
    String _idMenu_44 = this.getIdMenu();
    _builder.append(_idMenu_44, "\t");
    _builder.append(" ul ul li:last-child > span {");
    _builder.newLineIfNotEmpty();
    _builder.append("\t  ");
    _builder.append("border-bottom: 1px solid ");
    String _children_7 = this._color.getChildren("border");
    _builder.append(_children_7, "\t  ");
    _builder.append(";");
    _builder.newLineIfNotEmpty();
    _builder.append("\t");
    _builder.append("}");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("#");
    String _idMenu_45 = this.getIdMenu();
    _builder.append(_idMenu_45, "\t");
    _builder.append(" > ul > li > ul::after {");
    _builder.newLineIfNotEmpty();
    _builder.append("\t  ");
    _builder.append("position: absolute;");
    _builder.newLine();
    _builder.append("\t  ");
    _builder.append("display: block;");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("}");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("#");
    String _idMenu_46 = this.getIdMenu();
    _builder.append(_idMenu_46, "\t");
    _builder.append(" ul ul li.has-sub > a::after,");
    _builder.newLineIfNotEmpty();
    _builder.append("\t");
    _builder.append("#");
    String _idMenu_47 = this.getIdMenu();
    _builder.append(_idMenu_47, "\t");
    _builder.append(" ul ul li.has-sub > span::after {");
    _builder.newLineIfNotEmpty();
    _builder.append("\t  ");
    _builder.append("content: \"\";");
    _builder.newLine();
    _builder.append("\t  ");
    _builder.append("position: absolute;");
    _builder.newLine();
    _builder.append("\t  ");
    _builder.append("width: 6px;");
    _builder.newLine();
    _builder.append("\t  ");
    _builder.append("height: 6px;");
    _builder.newLine();
    _builder.append("\t  ");
    _builder.append("border-bottom: 2px solid ");
    String _children_8 = this._color.getChildren("color");
    _builder.append(_children_8, "\t  ");
    _builder.append(";");
    _builder.newLineIfNotEmpty();
    _builder.append("\t  ");
    _builder.append("border-right: 2px solid ");
    String _children_9 = this._color.getChildren("color");
    _builder.append(_children_9, "\t  ");
    _builder.append(";");
    _builder.newLineIfNotEmpty();
    _builder.append("\t  ");
    _builder.append("-webkit-transform: rotate(-45deg);");
    _builder.newLine();
    _builder.append("\t  ");
    _builder.append("-moz-transform: rotate(-45deg);");
    _builder.newLine();
    _builder.append("\t  ");
    _builder.append("-ms-transform: rotate(-45deg);");
    _builder.newLine();
    _builder.append("\t  ");
    _builder.append("-o-transform: rotate(-45deg);");
    _builder.newLine();
    _builder.append("\t  ");
    _builder.append("transform: rotate(-45deg);");
    _builder.newLine();
    _builder.append("\t  ");
    _builder.append("right: 17px;");
    _builder.newLine();
    _builder.append("\t  ");
    _builder.append("top: 14px;");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("}");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("#");
    String _idMenu_48 = this.getIdMenu();
    _builder.append(_idMenu_48, "\t");
    _builder.append(" ul ul li.has-sub.focus > a::after,");
    _builder.newLineIfNotEmpty();
    _builder.append("\t");
    _builder.append("#");
    String _idMenu_49 = this.getIdMenu();
    _builder.append(_idMenu_49, "\t");
    _builder.append(" ul ul li.has-sub:hover > a::after,");
    _builder.newLineIfNotEmpty();
    _builder.append("\t");
    _builder.append("#");
    String _idMenu_50 = this.getIdMenu();
    _builder.append(_idMenu_50, "\t");
    _builder.append(" ul ul li.has-sub.focus > span::after,");
    _builder.newLineIfNotEmpty();
    _builder.append("\t");
    _builder.append("#");
    String _idMenu_51 = this.getIdMenu();
    _builder.append(_idMenu_51, "\t");
    _builder.append(" ul ul li.has-sub:hover > span::after,");
    _builder.newLineIfNotEmpty();
    _builder.append("\t");
    _builder.append("#");
    String _idMenu_52 = this.getIdMenu();
    _builder.append(_idMenu_52, "\t");
    _builder.append(" ul ul li.has-sub.open > a::after,");
    _builder.newLineIfNotEmpty();
    _builder.append("\t");
    _builder.append("#");
    String _idMenu_53 = this.getIdMenu();
    _builder.append(_idMenu_53, "\t");
    _builder.append(" ul ul li.has-sub.open > span::after  {");
    _builder.newLineIfNotEmpty();
    _builder.append("\t  ");
    _builder.append("border-bottom-color: ");
    String _children_10 = this._color.getChildren("color-hover");
    _builder.append(_children_10, "\t  ");
    _builder.append(";");
    _builder.newLineIfNotEmpty();
    _builder.append("\t  ");
    _builder.append("border-right-color: ");
    String _children_11 = this._color.getChildren("color-hover");
    _builder.append(_children_11, "\t  ");
    _builder.append(";");
    _builder.newLineIfNotEmpty();
    _builder.append("\t");
    _builder.append("}");
    _builder.newLine();
    _builder.append("\t");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("#");
    String _idMenu_54 = this.getIdMenu();
    _builder.append(_idMenu_54, "\t");
    _builder.append(".align-center > ul {");
    _builder.newLineIfNotEmpty();
    _builder.append("\t  ");
    _builder.append("float: none;");
    _builder.newLine();
    _builder.append("\t  ");
    _builder.append("text-align: center;");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("}");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("#");
    String _idMenu_55 = this.getIdMenu();
    _builder.append(_idMenu_55, "\t");
    _builder.append(".align-center > ul > li {");
    _builder.newLineIfNotEmpty();
    _builder.append("\t  ");
    _builder.append("float: none;");
    _builder.newLine();
    _builder.append("\t  ");
    _builder.append("margin-left: -4px;");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("}");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("#");
    String _idMenu_56 = this.getIdMenu();
    _builder.append(_idMenu_56, "\t");
    _builder.append(".align-center ul ul {");
    _builder.newLineIfNotEmpty();
    _builder.append("\t  ");
    _builder.append("text-align: left;");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("}");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("#");
    String _idMenu_57 = this.getIdMenu();
    _builder.append(_idMenu_57, "\t");
    _builder.append(".align-right ul ul {");
    _builder.newLineIfNotEmpty();
    _builder.append("\t  ");
    _builder.append("text-align: right;");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("}");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("#");
    String _idMenu_58 = this.getIdMenu();
    _builder.append(_idMenu_58, "\t");
    _builder.append(".align-right > ul > li:first-child > a,");
    _builder.newLineIfNotEmpty();
    _builder.append("\t");
    _builder.append("#");
    String _idMenu_59 = this.getIdMenu();
    _builder.append(_idMenu_59, "\t");
    _builder.append(".align-right > ul > li:first-child > span {");
    _builder.newLineIfNotEmpty();
    _builder.append("\t  ");
    _builder.append("border-left-style: none;");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("}");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("#");
    String _idMenu_60 = this.getIdMenu();
    _builder.append(_idMenu_60, "\t");
    _builder.append(".align-right > ul > li:last-child > a,");
    _builder.newLineIfNotEmpty();
    _builder.append("\t");
    _builder.append("#");
    String _idMenu_61 = this.getIdMenu();
    _builder.append(_idMenu_61, "\t");
    _builder.append(".align-right > ul > li:last-child > span {");
    _builder.newLineIfNotEmpty();
    _builder.append("\t  ");
    _builder.append("border-left: 2px solid ");
    String _top_12 = this._color.getTop("border");
    _builder.append(_top_12, "\t  ");
    _builder.append(";");
    _builder.newLineIfNotEmpty();
    _builder.append("\t");
    _builder.append("}");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("#");
    String _idMenu_62 = this.getIdMenu();
    _builder.append(_idMenu_62, "\t");
    _builder.append(".align-right > ul > li.open > ul,");
    _builder.newLineIfNotEmpty();
    _builder.append("\t");
    _builder.append("#");
    String _idMenu_63 = this.getIdMenu();
    _builder.append(_idMenu_63, "\t");
    _builder.append(".align-right > ul > li:hover > ul {");
    _builder.newLineIfNotEmpty();
    _builder.append("\t  ");
    _builder.append("left: auto;");
    _builder.newLine();
    _builder.append("\t  ");
    _builder.append("right: 0;");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("}");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("#");
    String _idMenu_64 = this.getIdMenu();
    _builder.append(_idMenu_64, "\t");
    _builder.append(".align-right ul ul ul {");
    _builder.newLineIfNotEmpty();
    _builder.append("\t  ");
    _builder.append("padding-right: 8px;");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("}");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("#");
    String _idMenu_65 = this.getIdMenu();
    _builder.append(_idMenu_65, "\t");
    _builder.append(".align-right ul ul > li.open > ul,");
    _builder.newLineIfNotEmpty();
    _builder.append("\t");
    _builder.append("#");
    String _idMenu_66 = this.getIdMenu();
    _builder.append(_idMenu_66, "\t");
    _builder.append(".align-right ul ul > li:hover > ul {");
    _builder.newLineIfNotEmpty();
    _builder.append("\t  ");
    _builder.append("left: auto;");
    _builder.newLine();
    _builder.append("\t  ");
    _builder.append("right: 100%;");
    _builder.newLine();
    _builder.append("\t  ");
    _builder.append("opacity: 1;");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("}");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("#");
    String _idMenu_67 = this.getIdMenu();
    _builder.append(_idMenu_67, "\t");
    _builder.append(".align-right > ul > li {");
    _builder.newLineIfNotEmpty();
    _builder.append("\t  ");
    _builder.append("float: right;");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("}");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("#");
    String _idMenu_68 = this.getIdMenu();
    _builder.append(_idMenu_68, "\t");
    _builder.append(".align-right ul ul li.has-sub > a::after,");
    _builder.newLineIfNotEmpty();
    _builder.append("\t");
    _builder.append("#");
    String _idMenu_69 = this.getIdMenu();
    _builder.append(_idMenu_69, "\t");
    _builder.append(".align-right ul ul li.has-sub > span::after {");
    _builder.newLineIfNotEmpty();
    _builder.append("\t  ");
    _builder.append("right: auto;");
    _builder.newLine();
    _builder.append("\t  ");
    _builder.append("left: 17px;");
    _builder.newLine();
    _builder.append("\t  ");
    _builder.append("-webkit-transform: rotate(135deg);");
    _builder.newLine();
    _builder.append("\t  ");
    _builder.append("-moz-transform: rotate(135deg);");
    _builder.newLine();
    _builder.append("\t  ");
    _builder.append("-ms-transform: rotate(135deg);");
    _builder.newLine();
    _builder.append("\t  ");
    _builder.append("-o-transform: rotate(135deg);");
    _builder.newLine();
    _builder.append("\t  ");
    _builder.append("transform: rotate(135deg);");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("}");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("#");
    String _idMenu_70 = this.getIdMenu();
    _builder.append(_idMenu_70, "\t");
    _builder.append(".align-right ul ul li.has-sub.open > a::after,");
    _builder.newLineIfNotEmpty();
    _builder.append("\t");
    _builder.append("#");
    String _idMenu_71 = this.getIdMenu();
    _builder.append(_idMenu_71, "\t");
    _builder.append(".align-right ul ul li.has-sub.active > a::after,");
    _builder.newLineIfNotEmpty();
    _builder.append("\t");
    _builder.append("#");
    String _idMenu_72 = this.getIdMenu();
    _builder.append(_idMenu_72, "\t");
    _builder.append(".align-right ul ul li.has-sub.open > span::after,");
    _builder.newLineIfNotEmpty();
    _builder.append("\t");
    _builder.append("#");
    String _idMenu_73 = this.getIdMenu();
    _builder.append(_idMenu_73, "\t");
    _builder.append(".align-right ul ul li.has-sub.active > span::after {");
    _builder.newLineIfNotEmpty();
    _builder.append("\t  ");
    _builder.append("left:-6px;");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("}");
    _builder.newLine();
    _builder.append("</style>");
    _builder.newLine();
    return _builder;
  }
  
  protected CharSequence _colorComplex() {
    StringConcatenation _builder = new StringConcatenation();
    _builder.append("<style type=\"text/css\">");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("#");
    String _idMenu = this.getIdMenu();
    _builder.append(_idMenu, "\t");
    _builder.append(",");
    _builder.newLineIfNotEmpty();
    _builder.append("\t");
    _builder.append("#");
    String _idMenu_1 = this.getIdMenu();
    _builder.append(_idMenu_1, "\t");
    _builder.append(" ul,");
    _builder.newLineIfNotEmpty();
    _builder.append("\t");
    _builder.append("#");
    String _idMenu_2 = this.getIdMenu();
    _builder.append(_idMenu_2, "\t");
    _builder.append(" ul li,");
    _builder.newLineIfNotEmpty();
    _builder.append("\t");
    _builder.append("#");
    String _idMenu_3 = this.getIdMenu();
    _builder.append(_idMenu_3, "\t");
    _builder.append(" ul li a,");
    _builder.newLineIfNotEmpty();
    _builder.append("\t");
    _builder.append("#");
    String _idMenu_4 = this.getIdMenu();
    _builder.append(_idMenu_4, "\t");
    _builder.append(" ul li span {");
    _builder.newLineIfNotEmpty();
    _builder.append("\t  ");
    _builder.append("margin: 0;");
    _builder.newLine();
    _builder.append("\t  ");
    _builder.append("padding: 0;");
    _builder.newLine();
    _builder.append("\t  ");
    _builder.append("border: 0;");
    _builder.newLine();
    _builder.append("\t  ");
    _builder.append("list-style: none;");
    _builder.newLine();
    _builder.append("\t  ");
    _builder.append("line-height: 1;");
    _builder.newLine();
    _builder.append("\t  ");
    _builder.append("display: block;");
    _builder.newLine();
    _builder.append("\t  ");
    _builder.append("position: relative;");
    _builder.newLine();
    _builder.append("\t  ");
    _builder.append("-webkit-box-sizing: border-box;");
    _builder.newLine();
    _builder.append("\t  ");
    _builder.append("-moz-box-sizing: border-box;");
    _builder.newLine();
    _builder.append("\t  ");
    _builder.append("box-sizing: border-box;");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("}");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("#");
    String _idMenu_5 = this.getIdMenu();
    _builder.append(_idMenu_5, "\t");
    _builder.append(":after,");
    _builder.newLineIfNotEmpty();
    _builder.append("\t");
    _builder.append("#");
    String _idMenu_6 = this.getIdMenu();
    _builder.append(_idMenu_6, "\t");
    _builder.append(" > ul:after {");
    _builder.newLineIfNotEmpty();
    _builder.append("\t  ");
    _builder.append("content: \".\";");
    _builder.newLine();
    _builder.append("\t  ");
    _builder.append("display: block;");
    _builder.newLine();
    _builder.append("\t  ");
    _builder.append("clear: both;");
    _builder.newLine();
    _builder.append("\t  ");
    _builder.append("visibility: hidden;");
    _builder.newLine();
    _builder.append("\t  ");
    _builder.append("line-height: 0;");
    _builder.newLine();
    _builder.append("\t  ");
    _builder.append("height: 0;");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("}");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("#");
    String _idMenu_7 = this.getIdMenu();
    _builder.append(_idMenu_7, "\t");
    _builder.append(" {");
    _builder.newLineIfNotEmpty();
    _builder.append("\t  ");
    _builder.append("width: auto;");
    _builder.newLine();
    _builder.append("\t  ");
    _builder.append("background: ");
    String _top = this._color.getTop("background");
    _builder.append(_top, "\t  ");
    _builder.append(";");
    _builder.newLineIfNotEmpty();
    _builder.append("\t");
    _builder.append("}");
    _builder.newLine();
    _builder.append("\t");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("#");
    String _idMenu_8 = this.getIdMenu();
    _builder.append(_idMenu_8, "\t");
    _builder.append(" > ul > li {");
    _builder.newLineIfNotEmpty();
    _builder.append("\t  ");
    _builder.append("float: left;");
    _builder.newLine();
    _builder.append("\t  ");
    _builder.append("display: inline-block;");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("}");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("#");
    String _idMenu_9 = this.getIdMenu();
    _builder.append(_idMenu_9, "\t");
    _builder.append(" > ul > li > a ,");
    _builder.newLineIfNotEmpty();
    _builder.append("\t");
    _builder.append("#");
    String _idMenu_10 = this.getIdMenu();
    _builder.append(_idMenu_10, "\t");
    _builder.append(" > ul > li > span {");
    _builder.newLineIfNotEmpty();
    _builder.append("\t  ");
    _builder.append("padding: 10px 25px 13px 25px;");
    _builder.newLine();
    _builder.append("\t  ");
    _builder.append("border-top: 2px solid ");
    String _top_1 = this._color.getTop("border");
    _builder.append(_top_1, "\t  ");
    _builder.append(";");
    _builder.newLineIfNotEmpty();
    _builder.append("\t  ");
    _builder.append("border-bottom: 2px solid ");
    String _top_2 = this._color.getTop("border");
    _builder.append(_top_2, "\t  ");
    _builder.append(";");
    _builder.newLineIfNotEmpty();
    _builder.append("\t  ");
    _builder.append("border-right: 2px solid ");
    String _top_3 = this._color.getTop("border");
    _builder.append(_top_3, "\t  ");
    _builder.append(";");
    _builder.newLineIfNotEmpty();
    _builder.append("\t  ");
    _builder.append("text-decoration: none;");
    _builder.newLine();
    _builder.append("\t  ");
    _builder.append("color: ");
    String _top_4 = this._color.getTop("color");
    _builder.append(_top_4, "\t  ");
    _builder.append(";");
    _builder.newLineIfNotEmpty();
    _builder.append("\t  ");
    _builder.append("cursor:pointer;");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("}");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("#");
    String _idMenu_11 = this.getIdMenu();
    _builder.append(_idMenu_11, "\t");
    _builder.append(" > ul > li:first-child > a ,");
    _builder.newLineIfNotEmpty();
    _builder.append("\t");
    _builder.append("#");
    String _idMenu_12 = this.getIdMenu();
    _builder.append(_idMenu_12, "\t");
    _builder.append(" > ul > li:first-child > span {");
    _builder.newLineIfNotEmpty();
    _builder.append("\t  ");
    _builder.append("border-left: 2px solid ");
    String _top_5 = this._color.getTop("border");
    _builder.append(_top_5, "\t  ");
    _builder.append(";");
    _builder.newLineIfNotEmpty();
    _builder.append("\t");
    _builder.append("}");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("#");
    String _idMenu_13 = this.getIdMenu();
    _builder.append(_idMenu_13, "\t");
    _builder.append(" > ul > li.open > a,");
    _builder.newLineIfNotEmpty();
    _builder.append("\t");
    _builder.append("#");
    String _idMenu_14 = this.getIdMenu();
    _builder.append(_idMenu_14, "\t");
    _builder.append(" > ul > li.focus > a,");
    _builder.newLineIfNotEmpty();
    _builder.append("\t");
    _builder.append("#");
    String _idMenu_15 = this.getIdMenu();
    _builder.append(_idMenu_15, "\t");
    _builder.append(" > ul > li:hover > a,");
    _builder.newLineIfNotEmpty();
    _builder.append("\t");
    _builder.append("#");
    String _idMenu_16 = this.getIdMenu();
    _builder.append(_idMenu_16, "\t");
    _builder.append(" > ul > li > a:hover,");
    _builder.newLineIfNotEmpty();
    _builder.append("\t");
    _builder.append("#");
    String _idMenu_17 = this.getIdMenu();
    _builder.append(_idMenu_17, "\t");
    _builder.append(" > ul > li.active > a,");
    _builder.newLineIfNotEmpty();
    _builder.append("\t");
    _builder.append("#");
    String _idMenu_18 = this.getIdMenu();
    _builder.append(_idMenu_18, "\t");
    _builder.append(" > ul > li.open > span,");
    _builder.newLineIfNotEmpty();
    _builder.append("\t");
    _builder.append("#");
    String _idMenu_19 = this.getIdMenu();
    _builder.append(_idMenu_19, "\t");
    _builder.append(" > ul > li.focus > span,");
    _builder.newLineIfNotEmpty();
    _builder.append("\t");
    _builder.append("#");
    String _idMenu_20 = this.getIdMenu();
    _builder.append(_idMenu_20, "\t");
    _builder.append(" > ul > li:hover > span,");
    _builder.newLineIfNotEmpty();
    _builder.append("\t");
    _builder.append("#");
    String _idMenu_21 = this.getIdMenu();
    _builder.append(_idMenu_21, "\t");
    _builder.append(" > ul > li > span:hover,");
    _builder.newLineIfNotEmpty();
    _builder.append("\t");
    _builder.append("#");
    String _idMenu_22 = this.getIdMenu();
    _builder.append(_idMenu_22, "\t");
    _builder.append(" > ul > li.active > span {");
    _builder.newLineIfNotEmpty();
    _builder.append("\t  ");
    _builder.append("color: ");
    String _top_6 = this._color.getTop("color-hover");
    _builder.append(_top_6, "\t  ");
    _builder.append(";");
    _builder.newLineIfNotEmpty();
    _builder.append("\t  ");
    _builder.append("background: ");
    String _top_7 = this._color.getTop("background-hover");
    _builder.append(_top_7, "\t  ");
    _builder.append(";");
    _builder.newLineIfNotEmpty();
    _builder.append("\t");
    _builder.append("}");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("#");
    String _idMenu_23 = this.getIdMenu();
    _builder.append(_idMenu_23, "\t");
    _builder.append(" > ul > li.has-sub > a,");
    _builder.newLineIfNotEmpty();
    _builder.append("\t");
    _builder.append("#");
    String _idMenu_24 = this.getIdMenu();
    _builder.append(_idMenu_24, "\t");
    _builder.append(" > ul > li.has-sub > span {");
    _builder.newLineIfNotEmpty();
    _builder.append("\t  ");
    _builder.append("padding-right: 45px;");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("}");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("#");
    String _idMenu_25 = this.getIdMenu();
    _builder.append(_idMenu_25, "\t");
    _builder.append(" > ul > li.has-sub::after {");
    _builder.newLineIfNotEmpty();
    _builder.append("\t  ");
    _builder.append("content: \"\";");
    _builder.newLine();
    _builder.append("\t  ");
    _builder.append("position: absolute;");
    _builder.newLine();
    _builder.append("\t  ");
    _builder.append("right: 15px;");
    _builder.newLine();
    _builder.append("\t  ");
    _builder.append("top: 13px;");
    _builder.newLine();
    _builder.append("\t  ");
    _builder.append("width: 8px;");
    _builder.newLine();
    _builder.append("\t  ");
    _builder.append("height: 8px;");
    _builder.newLine();
    _builder.append("\t  ");
    _builder.append("border-bottom: 2px solid ");
    String _top_8 = this._color.getTop("color");
    _builder.append(_top_8, "\t  ");
    _builder.append(";");
    _builder.newLineIfNotEmpty();
    _builder.append("\t  ");
    _builder.append("border-right: 2px solid ");
    String _top_9 = this._color.getTop("color");
    _builder.append(_top_9, "\t  ");
    _builder.append(";");
    _builder.newLineIfNotEmpty();
    _builder.append("\t  ");
    _builder.append("content: \"\";");
    _builder.newLine();
    _builder.append("\t  ");
    _builder.append("-webkit-transform: rotate(45deg);");
    _builder.newLine();
    _builder.append("\t  ");
    _builder.append("-moz-transform: rotate(45deg);");
    _builder.newLine();
    _builder.append("\t  ");
    _builder.append("-ms-transform: rotate(45deg);");
    _builder.newLine();
    _builder.append("\t  ");
    _builder.append("-o-transform: rotate(45deg);");
    _builder.newLine();
    _builder.append("\t  ");
    _builder.append("transform: rotate(45deg);");
    _builder.newLine();
    _builder.append("\t  ");
    _builder.append("-moz-transition: all .3s ease;");
    _builder.newLine();
    _builder.append("\t  ");
    _builder.append("-ms-transition: all .3s ease;");
    _builder.newLine();
    _builder.append("\t  ");
    _builder.append("-o-transition: all .3s ease;");
    _builder.newLine();
    _builder.append("\t  ");
    _builder.append("transition: all .3s ease;");
    _builder.newLine();
    _builder.append("\t  ");
    _builder.append("-webkit-transition: all 0.3s ease;");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("}");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("#");
    String _idMenu_26 = this.getIdMenu();
    _builder.append(_idMenu_26, "\t");
    _builder.append(" > ul > li.has-sub.focus::after,");
    _builder.newLineIfNotEmpty();
    _builder.append("\t");
    _builder.append("#");
    String _idMenu_27 = this.getIdMenu();
    _builder.append(_idMenu_27, "\t");
    _builder.append(" > ul > li.has-sub:hover::after,");
    _builder.newLineIfNotEmpty();
    _builder.append("\t");
    _builder.append("#");
    String _idMenu_28 = this.getIdMenu();
    _builder.append(_idMenu_28, "\t");
    _builder.append(" > ul > li.has-sub.active::after{");
    _builder.newLineIfNotEmpty();
    _builder.append("\t  ");
    _builder.append("border-bottom-color: ");
    String _top_10 = this._color.getTop("color-hover");
    _builder.append(_top_10, "\t  ");
    _builder.append(";");
    _builder.newLineIfNotEmpty();
    _builder.append("\t  ");
    _builder.append("border-right-color: ");
    String _top_11 = this._color.getTop("color-hover");
    _builder.append(_top_11, "\t  ");
    _builder.append(";");
    _builder.newLineIfNotEmpty();
    _builder.append("\t");
    _builder.append("}");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("#");
    String _idMenu_29 = this.getIdMenu();
    _builder.append(_idMenu_29, "\t");
    _builder.append(" > ul > li.has-sub.open::after {");
    _builder.newLineIfNotEmpty();
    _builder.append("\t  ");
    _builder.append("border-bottom-color: ");
    String _top_12 = this._color.getTop("border");
    _builder.append(_top_12, "\t  ");
    _builder.append(";");
    _builder.newLineIfNotEmpty();
    _builder.append("\t  ");
    _builder.append("border-right-color: ");
    String _top_13 = this._color.getTop("border");
    _builder.append(_top_13, "\t  ");
    _builder.append(";");
    _builder.newLineIfNotEmpty();
    _builder.append("\t  ");
    _builder.append("background: ");
    String _top_14 = this._color.getTop("background-hover");
    _builder.append(_top_14, "\t  ");
    _builder.append(";");
    _builder.newLineIfNotEmpty();
    _builder.append("\t  ");
    _builder.append("top: 36px;");
    _builder.newLine();
    _builder.append("\t  ");
    _builder.append("right: 14px;");
    _builder.newLine();
    _builder.append("\t  ");
    _builder.append("width: 10px;");
    _builder.newLine();
    _builder.append("\t  ");
    _builder.append("height: 10px;");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("}");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("#");
    String _idMenu_30 = this.getIdMenu();
    _builder.append(_idMenu_30, "\t");
    _builder.append(" ul ul {");
    _builder.newLineIfNotEmpty();
    _builder.append("\t  ");
    _builder.append("position: absolute;");
    _builder.newLine();
    _builder.append("\t  ");
    _builder.append("left: -9999px;");
    _builder.newLine();
    _builder.append("\t  ");
    _builder.append("top: 60px;");
    _builder.newLine();
    _builder.append("\t  ");
    _builder.append("padding-top: 8px;");
    _builder.newLine();
    _builder.append("\t  ");
    _builder.append("font-size: 13px;");
    _builder.newLine();
    _builder.append("\t  ");
    _builder.append("opacity: 0;");
    _builder.newLine();
    _builder.append("\t  ");
    _builder.append("-webkit-transition: opacity 0.2s ease-in;");
    _builder.newLine();
    _builder.append("\t  ");
    _builder.append("-moz-transition: opacity 0.2s ease-in;");
    _builder.newLine();
    _builder.append("\t  ");
    _builder.append("-ms-transition: opacity 0.2s ease-in;");
    _builder.newLine();
    _builder.append("\t  ");
    _builder.append("-o-transition: opacity 0.2s ease-in;");
    _builder.newLine();
    _builder.append("\t  ");
    _builder.append("transition: opacity 0.2s ease-in;");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("}");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("#");
    String _idMenu_31 = this.getIdMenu();
    _builder.append(_idMenu_31, "\t");
    _builder.append(" > ul > li > ul {");
    _builder.newLineIfNotEmpty();
    _builder.append("\t  ");
    _builder.append("top: 120px;");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("}");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("#");
    String _idMenu_32 = this.getIdMenu();
    _builder.append(_idMenu_32, "\t");
    _builder.append(" > ul > li.open > ul {");
    _builder.newLineIfNotEmpty();
    _builder.append("\t  ");
    _builder.append("top: 100%;");
    _builder.newLine();
    _builder.append("\t  ");
    _builder.append("left: 0;");
    _builder.newLine();
    _builder.append("\t  ");
    _builder.append("opacity: 1;");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("}");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("#");
    String _idMenu_33 = this.getIdMenu();
    _builder.append(_idMenu_33, "\t");
    _builder.append(" ul ul ul {");
    _builder.newLineIfNotEmpty();
    _builder.append("\t  ");
    _builder.append("padding-top: 0;");
    _builder.newLine();
    _builder.append("\t  ");
    _builder.append("padding-left: 8px;");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("}");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("#");
    String _idMenu_34 = this.getIdMenu();
    _builder.append(_idMenu_34, "\t");
    _builder.append(" ul ul > li.open > ul {");
    _builder.newLineIfNotEmpty();
    _builder.append("\t  ");
    _builder.append("display:block;");
    _builder.newLine();
    _builder.append("\t  ");
    _builder.append("left: 180px;");
    _builder.newLine();
    _builder.append("\t  ");
    _builder.append("top: 0;");
    _builder.newLine();
    _builder.append("\t  ");
    _builder.append("opacity: 1;");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("}");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("#");
    String _idMenu_35 = this.getIdMenu();
    _builder.append(_idMenu_35, "\t");
    _builder.append(" ul ul li a,");
    _builder.newLineIfNotEmpty();
    _builder.append("\t");
    _builder.append("#");
    String _idMenu_36 = this.getIdMenu();
    _builder.append(_idMenu_36, "\t");
    _builder.append(" ul ul li span {");
    _builder.newLineIfNotEmpty();
    _builder.append("\t  ");
    _builder.append("text-decoration: none;");
    _builder.newLine();
    _builder.append("\t  ");
    _builder.append("padding: 11px 25px;");
    _builder.newLine();
    _builder.append("\t  ");
    _builder.append("width: 180px;");
    _builder.newLine();
    _builder.append("\t  ");
    _builder.append("color: ");
    String _children = this._color.getChildren("color");
    _builder.append(_children, "\t  ");
    _builder.append(";");
    _builder.newLineIfNotEmpty();
    _builder.append("\t  ");
    _builder.append("background: ");
    String _children_1 = this._color.getChildren("background");
    _builder.append(_children_1, "\t  ");
    _builder.append(";");
    _builder.newLineIfNotEmpty();
    _builder.append("\t  ");
    _builder.append("box-shadow: 0 2px 2px rgba(0, 0, 0, 0.1), 1px 1px 1px rgba(0, 0, 0, 0.1), -1px 1px 1px rgba(0, 0, 0, 0.1);");
    _builder.newLine();
    _builder.append("\t  ");
    _builder.append("border-left: 1px solid ");
    String _children_2 = this._color.getChildren("border");
    _builder.append(_children_2, "\t  ");
    _builder.append(";");
    _builder.newLineIfNotEmpty();
    _builder.append("\t  ");
    _builder.append("border-right: 1px solid ");
    String _children_3 = this._color.getChildren("border");
    _builder.append(_children_3, "\t  ");
    _builder.append(";");
    _builder.newLineIfNotEmpty();
    _builder.append("\t  ");
    _builder.append("cursor:pointer;");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("}");
    _builder.newLine();
    _builder.append("\t");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("#");
    String _idMenu_37 = this.getIdMenu();
    _builder.append(_idMenu_37, "\t");
    _builder.append(" ul ul li.open > a,");
    _builder.newLineIfNotEmpty();
    _builder.append("\t");
    _builder.append("#");
    String _idMenu_38 = this.getIdMenu();
    _builder.append(_idMenu_38, "\t");
    _builder.append(" ul ul li.focus > a,");
    _builder.newLineIfNotEmpty();
    _builder.append("\t");
    _builder.append("#");
    String _idMenu_39 = this.getIdMenu();
    _builder.append(_idMenu_39, "\t");
    _builder.append(" ul ul li:hover > a,");
    _builder.newLineIfNotEmpty();
    _builder.append("\t");
    _builder.append("#");
    String _idMenu_40 = this.getIdMenu();
    _builder.append(_idMenu_40, "\t");
    _builder.append(" ul ul li.active > a,");
    _builder.newLineIfNotEmpty();
    _builder.append("\t");
    _builder.append("#");
    String _idMenu_41 = this.getIdMenu();
    _builder.append(_idMenu_41, "\t");
    _builder.append(" ul ul li.open > span,");
    _builder.newLineIfNotEmpty();
    _builder.append("\t");
    _builder.append("#");
    String _idMenu_42 = this.getIdMenu();
    _builder.append(_idMenu_42, "\t");
    _builder.append(" ul ul li.focus > span,");
    _builder.newLineIfNotEmpty();
    _builder.append("\t");
    _builder.append("#");
    String _idMenu_43 = this.getIdMenu();
    _builder.append(_idMenu_43, "\t");
    _builder.append(" ul ul li:hover > span,");
    _builder.newLineIfNotEmpty();
    _builder.append("\t");
    _builder.append("#");
    String _idMenu_44 = this.getIdMenu();
    _builder.append(_idMenu_44, "\t");
    _builder.append(" ul ul li.active > span {");
    _builder.newLineIfNotEmpty();
    _builder.append("\t  ");
    _builder.append("color: ");
    String _children_4 = this._color.getChildren("color-hover");
    _builder.append(_children_4, "\t  ");
    _builder.append(";");
    _builder.newLineIfNotEmpty();
    _builder.append("\t  ");
    _builder.append("background:");
    String _children_5 = this._color.getChildren("background-hover");
    _builder.append(_children_5, "\t  ");
    _builder.append(";");
    _builder.newLineIfNotEmpty();
    _builder.append("\t");
    _builder.append("}");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("#");
    String _idMenu_45 = this.getIdMenu();
    _builder.append(_idMenu_45, "\t");
    _builder.append(" ul ul li:first-child > a,");
    _builder.newLineIfNotEmpty();
    _builder.append("\t");
    _builder.append("#");
    String _idMenu_46 = this.getIdMenu();
    _builder.append(_idMenu_46, "\t");
    _builder.append(" ul ul li:first-child > span {");
    _builder.newLineIfNotEmpty();
    _builder.append("\t  ");
    _builder.append("border-top-left-radius: 3px;");
    _builder.newLine();
    _builder.append("\t  ");
    _builder.append("border-top-right-radius: 3px;");
    _builder.newLine();
    _builder.append("\t  ");
    _builder.append("border-top: 1px solid ");
    String _children_6 = this._color.getChildren("border");
    _builder.append(_children_6, "\t  ");
    _builder.append(";");
    _builder.newLineIfNotEmpty();
    _builder.append("\t");
    _builder.append("}");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("#");
    String _idMenu_47 = this.getIdMenu();
    _builder.append(_idMenu_47, "\t");
    _builder.append(" ul ul li:last-child > a,");
    _builder.newLineIfNotEmpty();
    _builder.append("\t");
    _builder.append("#");
    String _idMenu_48 = this.getIdMenu();
    _builder.append(_idMenu_48, "\t");
    _builder.append(" ul ul li:last-child > span {");
    _builder.newLineIfNotEmpty();
    _builder.append("\t  ");
    _builder.append("border-bottom-left-radius: 3px;");
    _builder.newLine();
    _builder.append("\t  ");
    _builder.append("border-bottom-right-radius: 3px;");
    _builder.newLine();
    _builder.append("\t  ");
    _builder.append("border-bottom: 1px solid ");
    String _children_7 = this._color.getChildren("border");
    _builder.append(_children_7, "\t  ");
    _builder.append(";");
    _builder.newLineIfNotEmpty();
    _builder.append("\t");
    _builder.append("}");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("#");
    String _idMenu_49 = this.getIdMenu();
    _builder.append(_idMenu_49, "\t");
    _builder.append(" > ul > li > ul::after {");
    _builder.newLineIfNotEmpty();
    _builder.append("\t  ");
    _builder.append("position: absolute;");
    _builder.newLine();
    _builder.append("\t  ");
    _builder.append("display: block;");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("}");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("#");
    String _idMenu_50 = this.getIdMenu();
    _builder.append(_idMenu_50, "\t");
    _builder.append(" ul ul li.has-sub > a::after,");
    _builder.newLineIfNotEmpty();
    _builder.append("\t");
    _builder.append("#");
    String _idMenu_51 = this.getIdMenu();
    _builder.append(_idMenu_51, "\t");
    _builder.append(" ul ul li.has-sub > span::after {");
    _builder.newLineIfNotEmpty();
    _builder.append("\t  ");
    _builder.append("content: \"\";");
    _builder.newLine();
    _builder.append("\t  ");
    _builder.append("position: absolute;");
    _builder.newLine();
    _builder.append("\t  ");
    _builder.append("width: 6px;");
    _builder.newLine();
    _builder.append("\t  ");
    _builder.append("height: 6px;");
    _builder.newLine();
    _builder.append("\t  ");
    _builder.append("border-bottom: 2px solid ");
    String _children_8 = this._color.getChildren("color");
    _builder.append(_children_8, "\t  ");
    _builder.append(";");
    _builder.newLineIfNotEmpty();
    _builder.append("\t  ");
    _builder.append("border-right: 2px solid ");
    String _children_9 = this._color.getChildren("color");
    _builder.append(_children_9, "\t  ");
    _builder.append(";");
    _builder.newLineIfNotEmpty();
    _builder.append("\t  ");
    _builder.append("-webkit-transform: rotate(-45deg);");
    _builder.newLine();
    _builder.append("\t  ");
    _builder.append("-moz-transform: rotate(-45deg);");
    _builder.newLine();
    _builder.append("\t  ");
    _builder.append("-ms-transform: rotate(-45deg);");
    _builder.newLine();
    _builder.append("\t  ");
    _builder.append("-o-transform: rotate(-45deg);");
    _builder.newLine();
    _builder.append("\t  ");
    _builder.append("transform: rotate(-45deg);");
    _builder.newLine();
    _builder.append("\t  ");
    _builder.append("right: 17px;");
    _builder.newLine();
    _builder.append("\t  ");
    _builder.append("top: 14px;");
    _builder.newLine();
    _builder.append("\t  ");
    _builder.append("-moz-transition: all .2s ease;");
    _builder.newLine();
    _builder.append("\t  ");
    _builder.append("-ms-transition: all .2s ease;");
    _builder.newLine();
    _builder.append("\t  ");
    _builder.append("-o-transition: all .2s ease;");
    _builder.newLine();
    _builder.append("\t  ");
    _builder.append("transition: all .2s ease;");
    _builder.newLine();
    _builder.append("\t  ");
    _builder.append("-webkit-transition: -webkit-transform 0.2s ease, right 0.2s ease;");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("}");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("#");
    String _idMenu_52 = this.getIdMenu();
    _builder.append(_idMenu_52, "\t");
    _builder.append(" ul ul li.has-sub.focus > a::after,");
    _builder.newLineIfNotEmpty();
    _builder.append("\t");
    _builder.append("#");
    String _idMenu_53 = this.getIdMenu();
    _builder.append(_idMenu_53, "\t");
    _builder.append(" ul ul li.has-sub:hover > a::after,");
    _builder.newLineIfNotEmpty();
    _builder.append("\t");
    _builder.append("#");
    String _idMenu_54 = this.getIdMenu();
    _builder.append(_idMenu_54, "\t");
    _builder.append(" ul ul li.has-sub.focus > span::after,");
    _builder.newLineIfNotEmpty();
    _builder.append("\t");
    _builder.append("#");
    String _idMenu_55 = this.getIdMenu();
    _builder.append(_idMenu_55, "\t");
    _builder.append(" ul ul li.has-sub:hover > span::after {");
    _builder.newLineIfNotEmpty();
    _builder.append("\t  ");
    _builder.append("border-bottom-color: ");
    String _children_10 = this._color.getChildren("color-hover");
    _builder.append(_children_10, "\t  ");
    _builder.append(";");
    _builder.newLineIfNotEmpty();
    _builder.append("\t  ");
    _builder.append("border-right-color: ");
    String _children_11 = this._color.getChildren("color-hover");
    _builder.append(_children_11, "\t  ");
    _builder.append(";");
    _builder.newLineIfNotEmpty();
    _builder.append("\t");
    _builder.append("}");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("#");
    String _idMenu_56 = this.getIdMenu();
    _builder.append(_idMenu_56, "\t");
    _builder.append(" ul ul li.has-sub.open > a::after,");
    _builder.newLineIfNotEmpty();
    _builder.append("\t");
    _builder.append("#");
    String _idMenu_57 = this.getIdMenu();
    _builder.append(_idMenu_57, "\t");
    _builder.append(" ul ul li.has-sub.open > span::after {");
    _builder.newLineIfNotEmpty();
    _builder.append("\t  ");
    _builder.append("right: -6px;");
    _builder.newLine();
    _builder.append("\t  ");
    _builder.append("top: 11px;");
    _builder.newLine();
    _builder.append("\t  ");
    _builder.append("width: 10px;");
    _builder.newLine();
    _builder.append("\t  ");
    _builder.append("height: 10px;");
    _builder.newLine();
    _builder.append("\t  ");
    _builder.append("background:");
    String _children_12 = this._color.getChildren("background-hover");
    _builder.append(_children_12, "\t  ");
    _builder.append(";");
    _builder.newLineIfNotEmpty();
    _builder.append("\t  ");
    _builder.append("border-bottom: 1px solid ");
    String _children_13 = this._color.getChildren("border");
    _builder.append(_children_13, "\t  ");
    _builder.append("000;");
    _builder.newLineIfNotEmpty();
    _builder.append("\t  ");
    _builder.append("border-right: 1px solid ");
    String _children_14 = this._color.getChildren("border");
    _builder.append(_children_14, "\t  ");
    _builder.append("000;");
    _builder.newLineIfNotEmpty();
    _builder.append("\t");
    _builder.append("}");
    _builder.newLine();
    _builder.append("\t");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("#");
    String _idMenu_58 = this.getIdMenu();
    _builder.append(_idMenu_58, "\t");
    _builder.append(".align-center > ul {");
    _builder.newLineIfNotEmpty();
    _builder.append("\t  ");
    _builder.append("float: none;");
    _builder.newLine();
    _builder.append("\t  ");
    _builder.append("text-align: center;");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("}");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("#");
    String _idMenu_59 = this.getIdMenu();
    _builder.append(_idMenu_59, "\t");
    _builder.append(".align-center > ul > li {");
    _builder.newLineIfNotEmpty();
    _builder.append("\t  ");
    _builder.append("float: none;");
    _builder.newLine();
    _builder.append("\t  ");
    _builder.append("margin-left: -4px;");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("}");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("#");
    String _idMenu_60 = this.getIdMenu();
    _builder.append(_idMenu_60, "\t");
    _builder.append(".align-center ul ul {");
    _builder.newLineIfNotEmpty();
    _builder.append("\t  ");
    _builder.append("text-align: left;");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("}");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("#");
    String _idMenu_61 = this.getIdMenu();
    _builder.append(_idMenu_61, "\t");
    _builder.append(".align-right ul ul {");
    _builder.newLineIfNotEmpty();
    _builder.append("\t  ");
    _builder.append("text-align: right;");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("}");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("#");
    String _idMenu_62 = this.getIdMenu();
    _builder.append(_idMenu_62, "\t");
    _builder.append(".align-right > ul > li:first-child > a,");
    _builder.newLineIfNotEmpty();
    _builder.append("\t");
    _builder.append("#");
    String _idMenu_63 = this.getIdMenu();
    _builder.append(_idMenu_63, "\t");
    _builder.append(".align-right > ul > li:first-child > span {");
    _builder.newLineIfNotEmpty();
    _builder.append("\t  ");
    _builder.append("border-left-style: none;");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("}");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("#");
    String _idMenu_64 = this.getIdMenu();
    _builder.append(_idMenu_64, "\t");
    _builder.append(".align-right > ul > li:last-child > a,");
    _builder.newLineIfNotEmpty();
    _builder.append("\t");
    _builder.append("#");
    String _idMenu_65 = this.getIdMenu();
    _builder.append(_idMenu_65, "\t");
    _builder.append(".align-right > ul > li:last-child > span {");
    _builder.newLineIfNotEmpty();
    _builder.append("\t  ");
    _builder.append("border-left: 2px solid ");
    String _top_15 = this._color.getTop("border");
    _builder.append(_top_15, "\t  ");
    _builder.append(";");
    _builder.newLineIfNotEmpty();
    _builder.append("\t");
    _builder.append("}");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("#");
    String _idMenu_66 = this.getIdMenu();
    _builder.append(_idMenu_66, "\t");
    _builder.append(".align-right > ul > li.open > ul,");
    _builder.newLineIfNotEmpty();
    _builder.append("\t");
    _builder.append("#");
    String _idMenu_67 = this.getIdMenu();
    _builder.append(_idMenu_67, "\t");
    _builder.append(".align-right > ul > li:hover > ul {");
    _builder.newLineIfNotEmpty();
    _builder.append("\t  ");
    _builder.append("left: auto;");
    _builder.newLine();
    _builder.append("\t  ");
    _builder.append("right: 0;");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("}");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("#");
    String _idMenu_68 = this.getIdMenu();
    _builder.append(_idMenu_68, "\t");
    _builder.append(".align-right ul ul ul {");
    _builder.newLineIfNotEmpty();
    _builder.append("\t  ");
    _builder.append("padding-right: 8px;");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("}");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("#");
    String _idMenu_69 = this.getIdMenu();
    _builder.append(_idMenu_69, "\t");
    _builder.append(".align-right ul ul > li.open > ul,");
    _builder.newLineIfNotEmpty();
    _builder.append("\t");
    _builder.append("#");
    String _idMenu_70 = this.getIdMenu();
    _builder.append(_idMenu_70, "\t");
    _builder.append(".align-right ul ul > li:hover > ul {");
    _builder.newLineIfNotEmpty();
    _builder.append("\t  ");
    _builder.append("left: auto;");
    _builder.newLine();
    _builder.append("\t  ");
    _builder.append("right: 100%;");
    _builder.newLine();
    _builder.append("\t  ");
    _builder.append("opacity: 1;");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("}");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("#");
    String _idMenu_71 = this.getIdMenu();
    _builder.append(_idMenu_71, "\t");
    _builder.append(".align-right > ul > li {");
    _builder.newLineIfNotEmpty();
    _builder.append("\t  ");
    _builder.append("float: right;");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("}");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("#");
    String _idMenu_72 = this.getIdMenu();
    _builder.append(_idMenu_72, "\t");
    _builder.append(".align-right ul ul li.has-sub > a::after,");
    _builder.newLineIfNotEmpty();
    _builder.append("\t");
    _builder.append("#");
    String _idMenu_73 = this.getIdMenu();
    _builder.append(_idMenu_73, "\t");
    _builder.append(".align-right ul ul li.has-sub > span::after {");
    _builder.newLineIfNotEmpty();
    _builder.append("\t  ");
    _builder.append("right: auto;");
    _builder.newLine();
    _builder.append("\t  ");
    _builder.append("left: 17px;");
    _builder.newLine();
    _builder.append("\t  ");
    _builder.append("-webkit-transform: rotate(135deg);");
    _builder.newLine();
    _builder.append("\t  ");
    _builder.append("-moz-transform: rotate(135deg);");
    _builder.newLine();
    _builder.append("\t  ");
    _builder.append("-ms-transform: rotate(135deg);");
    _builder.newLine();
    _builder.append("\t  ");
    _builder.append("-o-transform: rotate(135deg);");
    _builder.newLine();
    _builder.append("\t  ");
    _builder.append("transform: rotate(135deg);");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("}");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("#");
    String _idMenu_74 = this.getIdMenu();
    _builder.append(_idMenu_74, "\t");
    _builder.append(".align-right ul ul li.has-sub.open > a::after,");
    _builder.newLineIfNotEmpty();
    _builder.append("\t");
    _builder.append("#");
    String _idMenu_75 = this.getIdMenu();
    _builder.append(_idMenu_75, "\t");
    _builder.append(".align-right ul ul li.has-sub.active > a::after,");
    _builder.newLineIfNotEmpty();
    _builder.append("\t");
    _builder.append("#");
    String _idMenu_76 = this.getIdMenu();
    _builder.append(_idMenu_76, "\t");
    _builder.append(".align-right ul ul li.has-sub.open > span::after,");
    _builder.newLineIfNotEmpty();
    _builder.append("\t");
    _builder.append("#");
    String _idMenu_77 = this.getIdMenu();
    _builder.append(_idMenu_77, "\t");
    _builder.append(".align-right ul ul li.has-sub.active > span::after {");
    _builder.newLineIfNotEmpty();
    _builder.append("\t  ");
    _builder.append("left:-6px;");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("}");
    _builder.newLine();
    _builder.append("</style>");
    _builder.newLine();
    return _builder;
  }
}
