/*
 * generated by Xtext
 */
package br.usp.icmc.amenu.validation;

import java.util.ArrayList;
import java.util.List;
import org.eclipse.emf.ecore.EPackage;

public class AbstractAMenuValidator extends org.eclipse.xtext.validation.AbstractDeclarativeValidator {

	@Override
	protected List<EPackage> getEPackages() {
	    List<EPackage> result = new ArrayList<EPackage>();
	    result.add(br.usp.icmc.amenu.aMenu.AMenuPackage.eINSTANCE);
		return result;
	}
}
