/**
 * generated by Xtext
 */
package br.usp.icmc.amenu.ui.contentassist;

import br.usp.icmc.amenu.ui.contentassist.AbstractAMenuProposalProvider;

/**
 * see http://www.eclipse.org/Xtext/documentation.html#contentAssist on how to customize content assistant
 */
@SuppressWarnings("all")
public class AMenuProposalProvider extends AbstractAMenuProposalProvider {
}
