/*
* generated by Xtext
*/
package br.usp.icmc.amenu;

import org.eclipse.xtext.junit4.IInjectorProvider;

import com.google.inject.Injector;

public class AMenuUiInjectorProvider implements IInjectorProvider {
	
	public Injector getInjector() {
		return br.usp.icmc.amenu.ui.internal.AMenuActivator.getInstance().getInjector("br.usp.icmc.amenu.AMenu");
	}
	
}
