/*
* generated by Xtext
*/
package br.usp.icmc.amenu;

/**
 * Initialization support for running Xtext languages 
 * without equinox extension registry
 */
public class AMenuStandaloneSetup extends AMenuStandaloneSetupGenerated{

	public static void doSetup() {
		new AMenuStandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}

