/*
 * generated by Xtext
 */
package br.usp.icmc.amenu;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class AMenuRuntimeModule extends br.usp.icmc.amenu.AbstractAMenuRuntimeModule {

}
