/*
* generated by Xtext
*/
package br.usp.icmc.amenu.services;

import com.google.inject.Singleton;
import com.google.inject.Inject;

import java.util.List;

import org.eclipse.xtext.*;
import org.eclipse.xtext.service.GrammarProvider;
import org.eclipse.xtext.service.AbstractElementFinder.*;

import org.eclipse.xtext.common.services.TerminalsGrammarAccess;

@Singleton
public class AMenuGrammarAccess extends AbstractGrammarElementFinder {
	
	
	public class MenuElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "Menu");
		private final UnorderedGroup cUnorderedGroup = (UnorderedGroup)rule.eContents().get(1);
		private final Group cGroup_0 = (Group)cUnorderedGroup.eContents().get(0);
		private final Keyword cIdKeyword_0_0 = (Keyword)cGroup_0.eContents().get(0);
		private final Keyword cEqualsSignKeyword_0_1 = (Keyword)cGroup_0.eContents().get(1);
		private final Assignment cNameAssignment_0_2 = (Assignment)cGroup_0.eContents().get(2);
		private final RuleCall cNameIDTerminalRuleCall_0_2_0 = (RuleCall)cNameAssignment_0_2.eContents().get(0);
		private final Keyword cSemicolonKeyword_0_3 = (Keyword)cGroup_0.eContents().get(3);
		private final Group cGroup_1 = (Group)cUnorderedGroup.eContents().get(1);
		private final Keyword cTypeKeyword_1_0 = (Keyword)cGroup_1.eContents().get(0);
		private final Keyword cEqualsSignKeyword_1_1 = (Keyword)cGroup_1.eContents().get(1);
		private final Assignment cTypeAssignment_1_2 = (Assignment)cGroup_1.eContents().get(2);
		private final RuleCall cTypeTypeEnumRuleCall_1_2_0 = (RuleCall)cTypeAssignment_1_2.eContents().get(0);
		private final Keyword cSemicolonKeyword_1_3 = (Keyword)cGroup_1.eContents().get(3);
		private final Group cGroup_2 = (Group)cUnorderedGroup.eContents().get(2);
		private final Keyword cStyleKeyword_2_0 = (Keyword)cGroup_2.eContents().get(0);
		private final Keyword cEqualsSignKeyword_2_1 = (Keyword)cGroup_2.eContents().get(1);
		private final Assignment cStyleAssignment_2_2 = (Assignment)cGroup_2.eContents().get(2);
		private final RuleCall cStyleStyleEnumRuleCall_2_2_0 = (RuleCall)cStyleAssignment_2_2.eContents().get(0);
		private final Keyword cSemicolonKeyword_2_3 = (Keyword)cGroup_2.eContents().get(3);
		private final Group cGroup_3 = (Group)cUnorderedGroup.eContents().get(3);
		private final Keyword cPositionKeyword_3_0 = (Keyword)cGroup_3.eContents().get(0);
		private final Keyword cEqualsSignKeyword_3_1 = (Keyword)cGroup_3.eContents().get(1);
		private final Assignment cPositionAssignment_3_2 = (Assignment)cGroup_3.eContents().get(2);
		private final RuleCall cPositionPositionEnumRuleCall_3_2_0 = (RuleCall)cPositionAssignment_3_2.eContents().get(0);
		private final Keyword cSemicolonKeyword_3_3 = (Keyword)cGroup_3.eContents().get(3);
		private final Group cGroup_4 = (Group)cUnorderedGroup.eContents().get(4);
		private final Keyword cClassKeyword_4_0 = (Keyword)cGroup_4.eContents().get(0);
		private final Keyword cEqualsSignKeyword_4_1 = (Keyword)cGroup_4.eContents().get(1);
		private final Assignment cDecoratorAssignment_4_2 = (Assignment)cGroup_4.eContents().get(2);
		private final RuleCall cDecoratorSTRINGTerminalRuleCall_4_2_0 = (RuleCall)cDecoratorAssignment_4_2.eContents().get(0);
		private final Keyword cSemicolonKeyword_4_3 = (Keyword)cGroup_4.eContents().get(3);
		private final Group cGroup_5 = (Group)cUnorderedGroup.eContents().get(5);
		private final Keyword cConfigKeyword_5_0 = (Keyword)cGroup_5.eContents().get(0);
		private final Keyword cEqualsSignKeyword_5_1 = (Keyword)cGroup_5.eContents().get(1);
		private final Keyword cLeftSquareBracketKeyword_5_2 = (Keyword)cGroup_5.eContents().get(2);
		private final Assignment cConfigurationAssignment_5_3 = (Assignment)cGroup_5.eContents().get(3);
		private final RuleCall cConfigurationConfigurationsParserRuleCall_5_3_0 = (RuleCall)cConfigurationAssignment_5_3.eContents().get(0);
		private final Keyword cRightSquareBracketKeyword_5_4 = (Keyword)cGroup_5.eContents().get(4);
		private final Keyword cSemicolonKeyword_5_5 = (Keyword)cGroup_5.eContents().get(5);
		private final Group cGroup_6 = (Group)cUnorderedGroup.eContents().get(6);
		private final Keyword cItemsKeyword_6_0 = (Keyword)cGroup_6.eContents().get(0);
		private final Keyword cEqualsSignKeyword_6_1 = (Keyword)cGroup_6.eContents().get(1);
		private final Keyword cLeftSquareBracketKeyword_6_2 = (Keyword)cGroup_6.eContents().get(2);
		private final Assignment cItemsAssignment_6_3 = (Assignment)cGroup_6.eContents().get(3);
		private final RuleCall cItemsItemParserRuleCall_6_3_0 = (RuleCall)cItemsAssignment_6_3.eContents().get(0);
		private final Group cGroup_6_4 = (Group)cGroup_6.eContents().get(4);
		private final Keyword cCommaKeyword_6_4_0 = (Keyword)cGroup_6_4.eContents().get(0);
		private final Assignment cItemsAssignment_6_4_1 = (Assignment)cGroup_6_4.eContents().get(1);
		private final RuleCall cItemsItemParserRuleCall_6_4_1_0 = (RuleCall)cItemsAssignment_6_4_1.eContents().get(0);
		private final Keyword cRightSquareBracketKeyword_6_5 = (Keyword)cGroup_6.eContents().get(5);
		private final Keyword cSemicolonKeyword_6_6 = (Keyword)cGroup_6.eContents().get(6);
		
		//Menu:
		//	("id" "=" name=ID ";")? & "type" "=" type=Type ";" & ("style" "=" style=Style ";")? & ("position" "="
		//	position=Position ";")? & ("class" "=" decorator=STRING ";")? & ("config" "=" "[" configuration=Configurations "]"
		//	";")? & "items" "=" "[" items+=Item ("," items+=Item)* "]" ";";
		public ParserRule getRule() { return rule; }

		//("id" "=" name=ID ";")? & "type" "=" type=Type ";" & ("style" "=" style=Style ";")? & ("position" "=" position=Position
		//";")? & ("class" "=" decorator=STRING ";")? & ("config" "=" "[" configuration=Configurations "]" ";")? & "items" "="
		//"[" items+=Item ("," items+=Item)* "]" ";"
		public UnorderedGroup getUnorderedGroup() { return cUnorderedGroup; }

		//("id" "=" name=ID ";")?
		public Group getGroup_0() { return cGroup_0; }

		//"id"
		public Keyword getIdKeyword_0_0() { return cIdKeyword_0_0; }

		//"="
		public Keyword getEqualsSignKeyword_0_1() { return cEqualsSignKeyword_0_1; }

		//name=ID
		public Assignment getNameAssignment_0_2() { return cNameAssignment_0_2; }

		//ID
		public RuleCall getNameIDTerminalRuleCall_0_2_0() { return cNameIDTerminalRuleCall_0_2_0; }

		//";"
		public Keyword getSemicolonKeyword_0_3() { return cSemicolonKeyword_0_3; }

		//"type" "=" type=Type ";"
		public Group getGroup_1() { return cGroup_1; }

		//"type"
		public Keyword getTypeKeyword_1_0() { return cTypeKeyword_1_0; }

		//"="
		public Keyword getEqualsSignKeyword_1_1() { return cEqualsSignKeyword_1_1; }

		//type=Type
		public Assignment getTypeAssignment_1_2() { return cTypeAssignment_1_2; }

		//Type
		public RuleCall getTypeTypeEnumRuleCall_1_2_0() { return cTypeTypeEnumRuleCall_1_2_0; }

		//";"
		public Keyword getSemicolonKeyword_1_3() { return cSemicolonKeyword_1_3; }

		//("style" "=" style=Style ";")?
		public Group getGroup_2() { return cGroup_2; }

		//"style"
		public Keyword getStyleKeyword_2_0() { return cStyleKeyword_2_0; }

		//"="
		public Keyword getEqualsSignKeyword_2_1() { return cEqualsSignKeyword_2_1; }

		//style=Style
		public Assignment getStyleAssignment_2_2() { return cStyleAssignment_2_2; }

		//Style
		public RuleCall getStyleStyleEnumRuleCall_2_2_0() { return cStyleStyleEnumRuleCall_2_2_0; }

		//";"
		public Keyword getSemicolonKeyword_2_3() { return cSemicolonKeyword_2_3; }

		//("position" "=" position=Position ";")?
		public Group getGroup_3() { return cGroup_3; }

		//"position"
		public Keyword getPositionKeyword_3_0() { return cPositionKeyword_3_0; }

		//"="
		public Keyword getEqualsSignKeyword_3_1() { return cEqualsSignKeyword_3_1; }

		//position=Position
		public Assignment getPositionAssignment_3_2() { return cPositionAssignment_3_2; }

		//Position
		public RuleCall getPositionPositionEnumRuleCall_3_2_0() { return cPositionPositionEnumRuleCall_3_2_0; }

		//";"
		public Keyword getSemicolonKeyword_3_3() { return cSemicolonKeyword_3_3; }

		//("class" "=" decorator=STRING ";")?
		public Group getGroup_4() { return cGroup_4; }

		//"class"
		public Keyword getClassKeyword_4_0() { return cClassKeyword_4_0; }

		//"="
		public Keyword getEqualsSignKeyword_4_1() { return cEqualsSignKeyword_4_1; }

		//decorator=STRING
		public Assignment getDecoratorAssignment_4_2() { return cDecoratorAssignment_4_2; }

		//STRING
		public RuleCall getDecoratorSTRINGTerminalRuleCall_4_2_0() { return cDecoratorSTRINGTerminalRuleCall_4_2_0; }

		//";"
		public Keyword getSemicolonKeyword_4_3() { return cSemicolonKeyword_4_3; }

		//("config" "=" "[" configuration=Configurations "]" ";")?
		public Group getGroup_5() { return cGroup_5; }

		//"config"
		public Keyword getConfigKeyword_5_0() { return cConfigKeyword_5_0; }

		//"="
		public Keyword getEqualsSignKeyword_5_1() { return cEqualsSignKeyword_5_1; }

		//"["
		public Keyword getLeftSquareBracketKeyword_5_2() { return cLeftSquareBracketKeyword_5_2; }

		//configuration=Configurations
		public Assignment getConfigurationAssignment_5_3() { return cConfigurationAssignment_5_3; }

		//Configurations
		public RuleCall getConfigurationConfigurationsParserRuleCall_5_3_0() { return cConfigurationConfigurationsParserRuleCall_5_3_0; }

		//"]"
		public Keyword getRightSquareBracketKeyword_5_4() { return cRightSquareBracketKeyword_5_4; }

		//";"
		public Keyword getSemicolonKeyword_5_5() { return cSemicolonKeyword_5_5; }

		//"items" "=" "[" items+=Item ("," items+=Item)* "]" ";"
		public Group getGroup_6() { return cGroup_6; }

		//"items"
		public Keyword getItemsKeyword_6_0() { return cItemsKeyword_6_0; }

		//"="
		public Keyword getEqualsSignKeyword_6_1() { return cEqualsSignKeyword_6_1; }

		//"["
		public Keyword getLeftSquareBracketKeyword_6_2() { return cLeftSquareBracketKeyword_6_2; }

		//items+=Item
		public Assignment getItemsAssignment_6_3() { return cItemsAssignment_6_3; }

		//Item
		public RuleCall getItemsItemParserRuleCall_6_3_0() { return cItemsItemParserRuleCall_6_3_0; }

		//("," items+=Item)*
		public Group getGroup_6_4() { return cGroup_6_4; }

		//","
		public Keyword getCommaKeyword_6_4_0() { return cCommaKeyword_6_4_0; }

		//items+=Item
		public Assignment getItemsAssignment_6_4_1() { return cItemsAssignment_6_4_1; }

		//Item
		public RuleCall getItemsItemParserRuleCall_6_4_1_0() { return cItemsItemParserRuleCall_6_4_1_0; }

		//"]"
		public Keyword getRightSquareBracketKeyword_6_5() { return cRightSquareBracketKeyword_6_5; }

		//";"
		public Keyword getSemicolonKeyword_6_6() { return cSemicolonKeyword_6_6; }
	}

	public class ConfigurationsElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "Configurations");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Alternatives cAlternatives_0 = (Alternatives)cGroup.eContents().get(0);
		private final Group cGroup_0_0 = (Group)cAlternatives_0.eContents().get(0);
		private final Keyword cTopKeyword_0_0_0 = (Keyword)cGroup_0_0.eContents().get(0);
		private final Assignment cConfig_topAssignment_0_0_1 = (Assignment)cGroup_0_0.eContents().get(1);
		private final RuleCall cConfig_topConfigParserRuleCall_0_0_1_0 = (RuleCall)cConfig_topAssignment_0_0_1.eContents().get(0);
		private final Group cGroup_0_1 = (Group)cAlternatives_0.eContents().get(1);
		private final Keyword cChildrenKeyword_0_1_0 = (Keyword)cGroup_0_1.eContents().get(0);
		private final Assignment cConfig_childrenAssignment_0_1_1 = (Assignment)cGroup_0_1.eContents().get(1);
		private final RuleCall cConfig_childrenConfigParserRuleCall_0_1_1_0 = (RuleCall)cConfig_childrenAssignment_0_1_1.eContents().get(0);
		private final Alternatives cAlternatives_1 = (Alternatives)cGroup.eContents().get(1);
		private final Group cGroup_1_0 = (Group)cAlternatives_1.eContents().get(0);
		private final Keyword cCommaKeyword_1_0_0 = (Keyword)cGroup_1_0.eContents().get(0);
		private final Keyword cTopKeyword_1_0_1 = (Keyword)cGroup_1_0.eContents().get(1);
		private final Assignment cConfig_topAssignment_1_0_2 = (Assignment)cGroup_1_0.eContents().get(2);
		private final RuleCall cConfig_topConfigParserRuleCall_1_0_2_0 = (RuleCall)cConfig_topAssignment_1_0_2.eContents().get(0);
		private final Group cGroup_1_1 = (Group)cAlternatives_1.eContents().get(1);
		private final Keyword cCommaKeyword_1_1_0 = (Keyword)cGroup_1_1.eContents().get(0);
		private final Keyword cChildrenKeyword_1_1_1 = (Keyword)cGroup_1_1.eContents().get(1);
		private final Assignment cConfig_childrenAssignment_1_1_2 = (Assignment)cGroup_1_1.eContents().get(2);
		private final RuleCall cConfig_childrenConfigParserRuleCall_1_1_2_0 = (RuleCall)cConfig_childrenAssignment_1_1_2.eContents().get(0);
		
		//Configurations:
		//	("top" config_top+=Config | "children" config_children+=Config) ("," "top" config_top+=Config | "," "children"
		//	config_children+=Config)*;
		public ParserRule getRule() { return rule; }

		//("top" config_top+=Config | "children" config_children+=Config) ("," "top" config_top+=Config | "," "children"
		//config_children+=Config)*
		public Group getGroup() { return cGroup; }

		//"top" config_top+=Config | "children" config_children+=Config
		public Alternatives getAlternatives_0() { return cAlternatives_0; }

		//"top" config_top+=Config
		public Group getGroup_0_0() { return cGroup_0_0; }

		//"top"
		public Keyword getTopKeyword_0_0_0() { return cTopKeyword_0_0_0; }

		//config_top+=Config
		public Assignment getConfig_topAssignment_0_0_1() { return cConfig_topAssignment_0_0_1; }

		//Config
		public RuleCall getConfig_topConfigParserRuleCall_0_0_1_0() { return cConfig_topConfigParserRuleCall_0_0_1_0; }

		//"children" config_children+=Config
		public Group getGroup_0_1() { return cGroup_0_1; }

		//"children"
		public Keyword getChildrenKeyword_0_1_0() { return cChildrenKeyword_0_1_0; }

		//config_children+=Config
		public Assignment getConfig_childrenAssignment_0_1_1() { return cConfig_childrenAssignment_0_1_1; }

		//Config
		public RuleCall getConfig_childrenConfigParserRuleCall_0_1_1_0() { return cConfig_childrenConfigParserRuleCall_0_1_1_0; }

		//("," "top" config_top+=Config | "," "children" config_children+=Config)*
		public Alternatives getAlternatives_1() { return cAlternatives_1; }

		//"," "top" config_top+=Config
		public Group getGroup_1_0() { return cGroup_1_0; }

		//","
		public Keyword getCommaKeyword_1_0_0() { return cCommaKeyword_1_0_0; }

		//"top"
		public Keyword getTopKeyword_1_0_1() { return cTopKeyword_1_0_1; }

		//config_top+=Config
		public Assignment getConfig_topAssignment_1_0_2() { return cConfig_topAssignment_1_0_2; }

		//Config
		public RuleCall getConfig_topConfigParserRuleCall_1_0_2_0() { return cConfig_topConfigParserRuleCall_1_0_2_0; }

		//"," "children" config_children+=Config
		public Group getGroup_1_1() { return cGroup_1_1; }

		//","
		public Keyword getCommaKeyword_1_1_0() { return cCommaKeyword_1_1_0; }

		//"children"
		public Keyword getChildrenKeyword_1_1_1() { return cChildrenKeyword_1_1_1; }

		//config_children+=Config
		public Assignment getConfig_childrenAssignment_1_1_2() { return cConfig_childrenAssignment_1_1_2; }

		//Config
		public RuleCall getConfig_childrenConfigParserRuleCall_1_1_2_0() { return cConfig_childrenConfigParserRuleCall_1_1_2_0; }
	}

	public class ConfigElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "Config");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cHyphenMinusKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Assignment cFeatureAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cFeatureFEATURETerminalRuleCall_1_0 = (RuleCall)cFeatureAssignment_1.eContents().get(0);
		private final Keyword cEqualsSignKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Assignment cColorAssignment_3 = (Assignment)cGroup.eContents().get(3);
		private final RuleCall cColorCOLORTerminalRuleCall_3_0 = (RuleCall)cColorAssignment_3.eContents().get(0);
		
		//Config:
		//	"-" feature=FEATURE "=" color=COLOR;
		public ParserRule getRule() { return rule; }

		//"-" feature=FEATURE "=" color=COLOR
		public Group getGroup() { return cGroup; }

		//"-"
		public Keyword getHyphenMinusKeyword_0() { return cHyphenMinusKeyword_0; }

		//feature=FEATURE
		public Assignment getFeatureAssignment_1() { return cFeatureAssignment_1; }

		//FEATURE
		public RuleCall getFeatureFEATURETerminalRuleCall_1_0() { return cFeatureFEATURETerminalRuleCall_1_0; }

		//"="
		public Keyword getEqualsSignKeyword_2() { return cEqualsSignKeyword_2; }

		//color=COLOR
		public Assignment getColorAssignment_3() { return cColorAssignment_3; }

		//COLOR
		public RuleCall getColorCOLORTerminalRuleCall_3_0() { return cColorCOLORTerminalRuleCall_3_0; }
	}

	public class ItemElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "Item");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cLeftCurlyBracketKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final UnorderedGroup cUnorderedGroup_1 = (UnorderedGroup)cGroup.eContents().get(1);
		private final Group cGroup_1_0 = (Group)cUnorderedGroup_1.eContents().get(0);
		private final Keyword cIdKeyword_1_0_0 = (Keyword)cGroup_1_0.eContents().get(0);
		private final Keyword cEqualsSignKeyword_1_0_1 = (Keyword)cGroup_1_0.eContents().get(1);
		private final Assignment cNameAssignment_1_0_2 = (Assignment)cGroup_1_0.eContents().get(2);
		private final RuleCall cNameIDTerminalRuleCall_1_0_2_0 = (RuleCall)cNameAssignment_1_0_2.eContents().get(0);
		private final Keyword cSemicolonKeyword_1_0_3 = (Keyword)cGroup_1_0.eContents().get(3);
		private final Group cGroup_1_1 = (Group)cUnorderedGroup_1.eContents().get(1);
		private final Keyword cClassKeyword_1_1_0 = (Keyword)cGroup_1_1.eContents().get(0);
		private final Keyword cEqualsSignKeyword_1_1_1 = (Keyword)cGroup_1_1.eContents().get(1);
		private final Assignment cDecoratorAssignment_1_1_2 = (Assignment)cGroup_1_1.eContents().get(2);
		private final RuleCall cDecoratorSTRINGTerminalRuleCall_1_1_2_0 = (RuleCall)cDecoratorAssignment_1_1_2.eContents().get(0);
		private final Keyword cSemicolonKeyword_1_1_3 = (Keyword)cGroup_1_1.eContents().get(3);
		private final Group cGroup_1_2 = (Group)cUnorderedGroup_1.eContents().get(2);
		private final Keyword cActionKeyword_1_2_0 = (Keyword)cGroup_1_2.eContents().get(0);
		private final Keyword cEqualsSignKeyword_1_2_1 = (Keyword)cGroup_1_2.eContents().get(1);
		private final Assignment cActionAssignment_1_2_2 = (Assignment)cGroup_1_2.eContents().get(2);
		private final RuleCall cActionSTRINGTerminalRuleCall_1_2_2_0 = (RuleCall)cActionAssignment_1_2_2.eContents().get(0);
		private final Keyword cSemicolonKeyword_1_2_3 = (Keyword)cGroup_1_2.eContents().get(3);
		private final Group cGroup_1_3 = (Group)cUnorderedGroup_1.eContents().get(3);
		private final Keyword cLabelKeyword_1_3_0 = (Keyword)cGroup_1_3.eContents().get(0);
		private final Keyword cEqualsSignKeyword_1_3_1 = (Keyword)cGroup_1_3.eContents().get(1);
		private final Assignment cLabelAssignment_1_3_2 = (Assignment)cGroup_1_3.eContents().get(2);
		private final RuleCall cLabelSTRINGTerminalRuleCall_1_3_2_0 = (RuleCall)cLabelAssignment_1_3_2.eContents().get(0);
		private final Keyword cSemicolonKeyword_1_3_3 = (Keyword)cGroup_1_3.eContents().get(3);
		private final Group cGroup_1_4 = (Group)cUnorderedGroup_1.eContents().get(4);
		private final Keyword cTitleKeyword_1_4_0 = (Keyword)cGroup_1_4.eContents().get(0);
		private final Keyword cEqualsSignKeyword_1_4_1 = (Keyword)cGroup_1_4.eContents().get(1);
		private final Assignment cTitleAssignment_1_4_2 = (Assignment)cGroup_1_4.eContents().get(2);
		private final RuleCall cTitleSTRINGTerminalRuleCall_1_4_2_0 = (RuleCall)cTitleAssignment_1_4_2.eContents().get(0);
		private final Keyword cSemicolonKeyword_1_4_3 = (Keyword)cGroup_1_4.eContents().get(3);
		private final Group cGroup_1_5 = (Group)cUnorderedGroup_1.eContents().get(5);
		private final Keyword cDirKeyword_1_5_0 = (Keyword)cGroup_1_5.eContents().get(0);
		private final Keyword cEqualsSignKeyword_1_5_1 = (Keyword)cGroup_1_5.eContents().get(1);
		private final Assignment cDirectionAssignment_1_5_2 = (Assignment)cGroup_1_5.eContents().get(2);
		private final RuleCall cDirectionDirectionEnumRuleCall_1_5_2_0 = (RuleCall)cDirectionAssignment_1_5_2.eContents().get(0);
		private final Keyword cSemicolonKeyword_1_5_3 = (Keyword)cGroup_1_5.eContents().get(3);
		private final Group cGroup_1_6 = (Group)cUnorderedGroup_1.eContents().get(6);
		private final Keyword cTargetKeyword_1_6_0 = (Keyword)cGroup_1_6.eContents().get(0);
		private final Keyword cEqualsSignKeyword_1_6_1 = (Keyword)cGroup_1_6.eContents().get(1);
		private final Assignment cTargetAssignment_1_6_2 = (Assignment)cGroup_1_6.eContents().get(2);
		private final RuleCall cTargetTargetEnumRuleCall_1_6_2_0 = (RuleCall)cTargetAssignment_1_6_2.eContents().get(0);
		private final Keyword cSemicolonKeyword_1_6_3 = (Keyword)cGroup_1_6.eContents().get(3);
		private final Group cGroup_1_7 = (Group)cUnorderedGroup_1.eContents().get(7);
		private final Keyword cIconKeyword_1_7_0 = (Keyword)cGroup_1_7.eContents().get(0);
		private final Keyword cEqualsSignKeyword_1_7_1 = (Keyword)cGroup_1_7.eContents().get(1);
		private final Assignment cIconAssignment_1_7_2 = (Assignment)cGroup_1_7.eContents().get(2);
		private final RuleCall cIconIconParserRuleCall_1_7_2_0 = (RuleCall)cIconAssignment_1_7_2.eContents().get(0);
		private final Keyword cSemicolonKeyword_1_7_3 = (Keyword)cGroup_1_7.eContents().get(3);
		private final Group cGroup_1_8 = (Group)cUnorderedGroup_1.eContents().get(8);
		private final Keyword cSubmenuKeyword_1_8_0 = (Keyword)cGroup_1_8.eContents().get(0);
		private final Keyword cEqualsSignKeyword_1_8_1 = (Keyword)cGroup_1_8.eContents().get(1);
		private final Assignment cSubmenuAssignment_1_8_2 = (Assignment)cGroup_1_8.eContents().get(2);
		private final RuleCall cSubmenuSubMenuParserRuleCall_1_8_2_0 = (RuleCall)cSubmenuAssignment_1_8_2.eContents().get(0);
		private final Keyword cSemicolonKeyword_1_8_3 = (Keyword)cGroup_1_8.eContents().get(3);
		private final Keyword cRightCurlyBracketKeyword_2 = (Keyword)cGroup.eContents().get(2);
		
		//Item:
		//	"{" (("id" "=" name=ID ";")? & ("class" "=" decorator=STRING ";")? & ("action" "=" action=STRING ";")? & "label" "="
		//	label=STRING ";" & ("title" "=" title=STRING ";")? & ("dir" "=" direction=Direction ";")? & ("target" "="
		//	target=Target ";")? & ("icon" "=" icon=Icon ";")? & ("submenu" "=" submenu=SubMenu ";")?) "}";
		public ParserRule getRule() { return rule; }

		//"{" (("id" "=" name=ID ";")? & ("class" "=" decorator=STRING ";")? & ("action" "=" action=STRING ";")? & "label" "="
		//label=STRING ";" & ("title" "=" title=STRING ";")? & ("dir" "=" direction=Direction ";")? & ("target" "=" target=Target
		//";")? & ("icon" "=" icon=Icon ";")? & ("submenu" "=" submenu=SubMenu ";")?) "}"
		public Group getGroup() { return cGroup; }

		//"{"
		public Keyword getLeftCurlyBracketKeyword_0() { return cLeftCurlyBracketKeyword_0; }

		//("id" "=" name=ID ";")? & ("class" "=" decorator=STRING ";")? & ("action" "=" action=STRING ";")? & "label" "="
		//label=STRING ";" & ("title" "=" title=STRING ";")? & ("dir" "=" direction=Direction ";")? & ("target" "=" target=Target
		//";")? & ("icon" "=" icon=Icon ";")? & ("submenu" "=" submenu=SubMenu ";")?
		public UnorderedGroup getUnorderedGroup_1() { return cUnorderedGroup_1; }

		//("id" "=" name=ID ";")?
		public Group getGroup_1_0() { return cGroup_1_0; }

		//"id"
		public Keyword getIdKeyword_1_0_0() { return cIdKeyword_1_0_0; }

		//"="
		public Keyword getEqualsSignKeyword_1_0_1() { return cEqualsSignKeyword_1_0_1; }

		//name=ID
		public Assignment getNameAssignment_1_0_2() { return cNameAssignment_1_0_2; }

		//ID
		public RuleCall getNameIDTerminalRuleCall_1_0_2_0() { return cNameIDTerminalRuleCall_1_0_2_0; }

		//";"
		public Keyword getSemicolonKeyword_1_0_3() { return cSemicolonKeyword_1_0_3; }

		//("class" "=" decorator=STRING ";")?
		public Group getGroup_1_1() { return cGroup_1_1; }

		//"class"
		public Keyword getClassKeyword_1_1_0() { return cClassKeyword_1_1_0; }

		//"="
		public Keyword getEqualsSignKeyword_1_1_1() { return cEqualsSignKeyword_1_1_1; }

		//decorator=STRING
		public Assignment getDecoratorAssignment_1_1_2() { return cDecoratorAssignment_1_1_2; }

		//STRING
		public RuleCall getDecoratorSTRINGTerminalRuleCall_1_1_2_0() { return cDecoratorSTRINGTerminalRuleCall_1_1_2_0; }

		//";"
		public Keyword getSemicolonKeyword_1_1_3() { return cSemicolonKeyword_1_1_3; }

		//("action" "=" action=STRING ";")?
		public Group getGroup_1_2() { return cGroup_1_2; }

		//"action"
		public Keyword getActionKeyword_1_2_0() { return cActionKeyword_1_2_0; }

		//"="
		public Keyword getEqualsSignKeyword_1_2_1() { return cEqualsSignKeyword_1_2_1; }

		//action=STRING
		public Assignment getActionAssignment_1_2_2() { return cActionAssignment_1_2_2; }

		//STRING
		public RuleCall getActionSTRINGTerminalRuleCall_1_2_2_0() { return cActionSTRINGTerminalRuleCall_1_2_2_0; }

		//";"
		public Keyword getSemicolonKeyword_1_2_3() { return cSemicolonKeyword_1_2_3; }

		//"label" "=" label=STRING ";"
		public Group getGroup_1_3() { return cGroup_1_3; }

		//"label"
		public Keyword getLabelKeyword_1_3_0() { return cLabelKeyword_1_3_0; }

		//"="
		public Keyword getEqualsSignKeyword_1_3_1() { return cEqualsSignKeyword_1_3_1; }

		//label=STRING
		public Assignment getLabelAssignment_1_3_2() { return cLabelAssignment_1_3_2; }

		//STRING
		public RuleCall getLabelSTRINGTerminalRuleCall_1_3_2_0() { return cLabelSTRINGTerminalRuleCall_1_3_2_0; }

		//";"
		public Keyword getSemicolonKeyword_1_3_3() { return cSemicolonKeyword_1_3_3; }

		//("title" "=" title=STRING ";")?
		public Group getGroup_1_4() { return cGroup_1_4; }

		//"title"
		public Keyword getTitleKeyword_1_4_0() { return cTitleKeyword_1_4_0; }

		//"="
		public Keyword getEqualsSignKeyword_1_4_1() { return cEqualsSignKeyword_1_4_1; }

		//title=STRING
		public Assignment getTitleAssignment_1_4_2() { return cTitleAssignment_1_4_2; }

		//STRING
		public RuleCall getTitleSTRINGTerminalRuleCall_1_4_2_0() { return cTitleSTRINGTerminalRuleCall_1_4_2_0; }

		//";"
		public Keyword getSemicolonKeyword_1_4_3() { return cSemicolonKeyword_1_4_3; }

		//("dir" "=" direction=Direction ";")?
		public Group getGroup_1_5() { return cGroup_1_5; }

		//"dir"
		public Keyword getDirKeyword_1_5_0() { return cDirKeyword_1_5_0; }

		//"="
		public Keyword getEqualsSignKeyword_1_5_1() { return cEqualsSignKeyword_1_5_1; }

		//direction=Direction
		public Assignment getDirectionAssignment_1_5_2() { return cDirectionAssignment_1_5_2; }

		//Direction
		public RuleCall getDirectionDirectionEnumRuleCall_1_5_2_0() { return cDirectionDirectionEnumRuleCall_1_5_2_0; }

		//";"
		public Keyword getSemicolonKeyword_1_5_3() { return cSemicolonKeyword_1_5_3; }

		//("target" "=" target=Target ";")?
		public Group getGroup_1_6() { return cGroup_1_6; }

		//"target"
		public Keyword getTargetKeyword_1_6_0() { return cTargetKeyword_1_6_0; }

		//"="
		public Keyword getEqualsSignKeyword_1_6_1() { return cEqualsSignKeyword_1_6_1; }

		//target=Target
		public Assignment getTargetAssignment_1_6_2() { return cTargetAssignment_1_6_2; }

		//Target
		public RuleCall getTargetTargetEnumRuleCall_1_6_2_0() { return cTargetTargetEnumRuleCall_1_6_2_0; }

		//";"
		public Keyword getSemicolonKeyword_1_6_3() { return cSemicolonKeyword_1_6_3; }

		//("icon" "=" icon=Icon ";")?
		public Group getGroup_1_7() { return cGroup_1_7; }

		//"icon"
		public Keyword getIconKeyword_1_7_0() { return cIconKeyword_1_7_0; }

		//"="
		public Keyword getEqualsSignKeyword_1_7_1() { return cEqualsSignKeyword_1_7_1; }

		//icon=Icon
		public Assignment getIconAssignment_1_7_2() { return cIconAssignment_1_7_2; }

		//Icon
		public RuleCall getIconIconParserRuleCall_1_7_2_0() { return cIconIconParserRuleCall_1_7_2_0; }

		//";"
		public Keyword getSemicolonKeyword_1_7_3() { return cSemicolonKeyword_1_7_3; }

		//("submenu" "=" submenu=SubMenu ";")?
		public Group getGroup_1_8() { return cGroup_1_8; }

		//"submenu"
		public Keyword getSubmenuKeyword_1_8_0() { return cSubmenuKeyword_1_8_0; }

		//"="
		public Keyword getEqualsSignKeyword_1_8_1() { return cEqualsSignKeyword_1_8_1; }

		//submenu=SubMenu
		public Assignment getSubmenuAssignment_1_8_2() { return cSubmenuAssignment_1_8_2; }

		//SubMenu
		public RuleCall getSubmenuSubMenuParserRuleCall_1_8_2_0() { return cSubmenuSubMenuParserRuleCall_1_8_2_0; }

		//";"
		public Keyword getSemicolonKeyword_1_8_3() { return cSemicolonKeyword_1_8_3; }

		//"}"
		public Keyword getRightCurlyBracketKeyword_2() { return cRightCurlyBracketKeyword_2; }
	}

	public class SubMenuElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "SubMenu");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cLeftCurlyBracketKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final UnorderedGroup cUnorderedGroup_1 = (UnorderedGroup)cGroup.eContents().get(1);
		private final Group cGroup_1_0 = (Group)cUnorderedGroup_1.eContents().get(0);
		private final Keyword cClassKeyword_1_0_0 = (Keyword)cGroup_1_0.eContents().get(0);
		private final Keyword cEqualsSignKeyword_1_0_1 = (Keyword)cGroup_1_0.eContents().get(1);
		private final Assignment cDecoratorAssignment_1_0_2 = (Assignment)cGroup_1_0.eContents().get(2);
		private final RuleCall cDecoratorSTRINGTerminalRuleCall_1_0_2_0 = (RuleCall)cDecoratorAssignment_1_0_2.eContents().get(0);
		private final Keyword cSemicolonKeyword_1_0_3 = (Keyword)cGroup_1_0.eContents().get(3);
		private final Group cGroup_1_1 = (Group)cUnorderedGroup_1.eContents().get(1);
		private final Keyword cItemsKeyword_1_1_0 = (Keyword)cGroup_1_1.eContents().get(0);
		private final Keyword cEqualsSignKeyword_1_1_1 = (Keyword)cGroup_1_1.eContents().get(1);
		private final Keyword cLeftSquareBracketKeyword_1_1_2 = (Keyword)cGroup_1_1.eContents().get(2);
		private final Group cGroup_1_1_3 = (Group)cGroup_1_1.eContents().get(3);
		private final Assignment cItemsAssignment_1_1_3_0 = (Assignment)cGroup_1_1_3.eContents().get(0);
		private final RuleCall cItemsItemParserRuleCall_1_1_3_0_0 = (RuleCall)cItemsAssignment_1_1_3_0.eContents().get(0);
		private final Group cGroup_1_1_3_1 = (Group)cGroup_1_1_3.eContents().get(1);
		private final Keyword cCommaKeyword_1_1_3_1_0 = (Keyword)cGroup_1_1_3_1.eContents().get(0);
		private final Assignment cItemsAssignment_1_1_3_1_1 = (Assignment)cGroup_1_1_3_1.eContents().get(1);
		private final RuleCall cItemsItemParserRuleCall_1_1_3_1_1_0 = (RuleCall)cItemsAssignment_1_1_3_1_1.eContents().get(0);
		private final Keyword cRightSquareBracketKeyword_1_1_4 = (Keyword)cGroup_1_1.eContents().get(4);
		private final Keyword cSemicolonKeyword_1_1_5 = (Keyword)cGroup_1_1.eContents().get(5);
		private final Keyword cRightCurlyBracketKeyword_2 = (Keyword)cGroup.eContents().get(2);
		
		//SubMenu:
		//	"{" (("class" "=" decorator=STRING ";")? / * ( 'id = ' name=ID ';' )? * / & "items" "=" "[" (items+=Item (","
		//	items+=Item)*) "]" ";") "}";
		public ParserRule getRule() { return rule; }

		//"{" (("class" "=" decorator=STRING ";")? / * ( 'id = ' name=ID ';' )? * / & "items" "=" "[" (items+=Item (","
		//items+=Item)*) "]" ";") "}"
		public Group getGroup() { return cGroup; }

		//"{"
		public Keyword getLeftCurlyBracketKeyword_0() { return cLeftCurlyBracketKeyword_0; }

		//("class" "=" decorator=STRING ";")? / * ( 'id = ' name=ID ';' )? * / & "items" "=" "[" (items+=Item ("," items+=Item)*)
		//"]" ";"
		public UnorderedGroup getUnorderedGroup_1() { return cUnorderedGroup_1; }

		//("class" "=" decorator=STRING ";")?
		public Group getGroup_1_0() { return cGroup_1_0; }

		//"class"
		public Keyword getClassKeyword_1_0_0() { return cClassKeyword_1_0_0; }

		//"="
		public Keyword getEqualsSignKeyword_1_0_1() { return cEqualsSignKeyword_1_0_1; }

		//decorator=STRING
		public Assignment getDecoratorAssignment_1_0_2() { return cDecoratorAssignment_1_0_2; }

		//STRING
		public RuleCall getDecoratorSTRINGTerminalRuleCall_1_0_2_0() { return cDecoratorSTRINGTerminalRuleCall_1_0_2_0; }

		//";"
		public Keyword getSemicolonKeyword_1_0_3() { return cSemicolonKeyword_1_0_3; }

		//"items" "=" "[" (items+=Item ("," items+=Item)*) "]" ";"
		public Group getGroup_1_1() { return cGroup_1_1; }

		//"items"
		public Keyword getItemsKeyword_1_1_0() { return cItemsKeyword_1_1_0; }

		//"="
		public Keyword getEqualsSignKeyword_1_1_1() { return cEqualsSignKeyword_1_1_1; }

		//"["
		public Keyword getLeftSquareBracketKeyword_1_1_2() { return cLeftSquareBracketKeyword_1_1_2; }

		//items+=Item ("," items+=Item)*
		public Group getGroup_1_1_3() { return cGroup_1_1_3; }

		//items+=Item
		public Assignment getItemsAssignment_1_1_3_0() { return cItemsAssignment_1_1_3_0; }

		//Item
		public RuleCall getItemsItemParserRuleCall_1_1_3_0_0() { return cItemsItemParserRuleCall_1_1_3_0_0; }

		//("," items+=Item)*
		public Group getGroup_1_1_3_1() { return cGroup_1_1_3_1; }

		//","
		public Keyword getCommaKeyword_1_1_3_1_0() { return cCommaKeyword_1_1_3_1_0; }

		//items+=Item
		public Assignment getItemsAssignment_1_1_3_1_1() { return cItemsAssignment_1_1_3_1_1; }

		//Item
		public RuleCall getItemsItemParserRuleCall_1_1_3_1_1_0() { return cItemsItemParserRuleCall_1_1_3_1_1_0; }

		//"]"
		public Keyword getRightSquareBracketKeyword_1_1_4() { return cRightSquareBracketKeyword_1_1_4; }

		//";"
		public Keyword getSemicolonKeyword_1_1_5() { return cSemicolonKeyword_1_1_5; }

		//"}"
		public Keyword getRightCurlyBracketKeyword_2() { return cRightCurlyBracketKeyword_2; }
	}

	public class IconElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "Icon");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cLeftCurlyBracketKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final UnorderedGroup cUnorderedGroup_1 = (UnorderedGroup)cGroup.eContents().get(1);
		private final Group cGroup_1_0 = (Group)cUnorderedGroup_1.eContents().get(0);
		private final Keyword cIdKeyword_1_0_0 = (Keyword)cGroup_1_0.eContents().get(0);
		private final Keyword cEqualsSignKeyword_1_0_1 = (Keyword)cGroup_1_0.eContents().get(1);
		private final Assignment cNameAssignment_1_0_2 = (Assignment)cGroup_1_0.eContents().get(2);
		private final RuleCall cNameIDTerminalRuleCall_1_0_2_0 = (RuleCall)cNameAssignment_1_0_2.eContents().get(0);
		private final Keyword cSemicolonKeyword_1_0_3 = (Keyword)cGroup_1_0.eContents().get(3);
		private final Group cGroup_1_1 = (Group)cUnorderedGroup_1.eContents().get(1);
		private final Keyword cPositionKeyword_1_1_0 = (Keyword)cGroup_1_1.eContents().get(0);
		private final Keyword cEqualsSignKeyword_1_1_1 = (Keyword)cGroup_1_1.eContents().get(1);
		private final Assignment cPositionAssignment_1_1_2 = (Assignment)cGroup_1_1.eContents().get(2);
		private final RuleCall cPositionPositionEnumRuleCall_1_1_2_0 = (RuleCall)cPositionAssignment_1_1_2.eContents().get(0);
		private final Keyword cSemicolonKeyword_1_1_3 = (Keyword)cGroup_1_1.eContents().get(3);
		private final Group cGroup_1_2 = (Group)cUnorderedGroup_1.eContents().get(2);
		private final Keyword cClassKeyword_1_2_0 = (Keyword)cGroup_1_2.eContents().get(0);
		private final Keyword cEqualsSignKeyword_1_2_1 = (Keyword)cGroup_1_2.eContents().get(1);
		private final Assignment cDecoratorAssignment_1_2_2 = (Assignment)cGroup_1_2.eContents().get(2);
		private final RuleCall cDecoratorSTRINGTerminalRuleCall_1_2_2_0 = (RuleCall)cDecoratorAssignment_1_2_2.eContents().get(0);
		private final Keyword cSemicolonKeyword_1_2_3 = (Keyword)cGroup_1_2.eContents().get(3);
		private final Group cGroup_1_3 = (Group)cUnorderedGroup_1.eContents().get(3);
		private final Keyword cTextAltKeyword_1_3_0 = (Keyword)cGroup_1_3.eContents().get(0);
		private final Keyword cEqualsSignKeyword_1_3_1 = (Keyword)cGroup_1_3.eContents().get(1);
		private final Assignment cText_altAssignment_1_3_2 = (Assignment)cGroup_1_3.eContents().get(2);
		private final RuleCall cText_altSTRINGTerminalRuleCall_1_3_2_0 = (RuleCall)cText_altAssignment_1_3_2.eContents().get(0);
		private final Keyword cSemicolonKeyword_1_3_3 = (Keyword)cGroup_1_3.eContents().get(3);
		private final Group cGroup_1_4 = (Group)cUnorderedGroup_1.eContents().get(4);
		private final Keyword cAddressKeyword_1_4_0 = (Keyword)cGroup_1_4.eContents().get(0);
		private final Keyword cEqualsSignKeyword_1_4_1 = (Keyword)cGroup_1_4.eContents().get(1);
		private final Assignment cAddressAssignment_1_4_2 = (Assignment)cGroup_1_4.eContents().get(2);
		private final RuleCall cAddressSTRINGTerminalRuleCall_1_4_2_0 = (RuleCall)cAddressAssignment_1_4_2.eContents().get(0);
		private final Keyword cSemicolonKeyword_1_4_3 = (Keyword)cGroup_1_4.eContents().get(3);
		private final Keyword cRightCurlyBracketKeyword_2 = (Keyword)cGroup.eContents().get(2);
		
		//Icon:
		//	"{" (("id" "=" name=ID ";")? & ("position" "=" position=Position ";")? & ("class" "=" decorator=STRING ";")? &
		//	"text-alt" "=" text_alt=STRING ";" & "address" "=" address=STRING ";") / * & ( features += Feature )* * / "}";
		public ParserRule getRule() { return rule; }

		//"{" (("id" "=" name=ID ";")? & ("position" "=" position=Position ";")? & ("class" "=" decorator=STRING ";")? &
		//"text-alt" "=" text_alt=STRING ";" & "address" "=" address=STRING ";") / * & ( features += Feature )* * / "}"
		public Group getGroup() { return cGroup; }

		//"{"
		public Keyword getLeftCurlyBracketKeyword_0() { return cLeftCurlyBracketKeyword_0; }

		//("id" "=" name=ID ";")? & ("position" "=" position=Position ";")? & ("class" "=" decorator=STRING ";")? & "text-alt" "="
		//text_alt=STRING ";" & "address" "=" address=STRING ";"
		public UnorderedGroup getUnorderedGroup_1() { return cUnorderedGroup_1; }

		//("id" "=" name=ID ";")?
		public Group getGroup_1_0() { return cGroup_1_0; }

		//"id"
		public Keyword getIdKeyword_1_0_0() { return cIdKeyword_1_0_0; }

		//"="
		public Keyword getEqualsSignKeyword_1_0_1() { return cEqualsSignKeyword_1_0_1; }

		//name=ID
		public Assignment getNameAssignment_1_0_2() { return cNameAssignment_1_0_2; }

		//ID
		public RuleCall getNameIDTerminalRuleCall_1_0_2_0() { return cNameIDTerminalRuleCall_1_0_2_0; }

		//";"
		public Keyword getSemicolonKeyword_1_0_3() { return cSemicolonKeyword_1_0_3; }

		//("position" "=" position=Position ";")?
		public Group getGroup_1_1() { return cGroup_1_1; }

		//"position"
		public Keyword getPositionKeyword_1_1_0() { return cPositionKeyword_1_1_0; }

		//"="
		public Keyword getEqualsSignKeyword_1_1_1() { return cEqualsSignKeyword_1_1_1; }

		//position=Position
		public Assignment getPositionAssignment_1_1_2() { return cPositionAssignment_1_1_2; }

		//Position
		public RuleCall getPositionPositionEnumRuleCall_1_1_2_0() { return cPositionPositionEnumRuleCall_1_1_2_0; }

		//";"
		public Keyword getSemicolonKeyword_1_1_3() { return cSemicolonKeyword_1_1_3; }

		//("class" "=" decorator=STRING ";")?
		public Group getGroup_1_2() { return cGroup_1_2; }

		//"class"
		public Keyword getClassKeyword_1_2_0() { return cClassKeyword_1_2_0; }

		//"="
		public Keyword getEqualsSignKeyword_1_2_1() { return cEqualsSignKeyword_1_2_1; }

		//decorator=STRING
		public Assignment getDecoratorAssignment_1_2_2() { return cDecoratorAssignment_1_2_2; }

		//STRING
		public RuleCall getDecoratorSTRINGTerminalRuleCall_1_2_2_0() { return cDecoratorSTRINGTerminalRuleCall_1_2_2_0; }

		//";"
		public Keyword getSemicolonKeyword_1_2_3() { return cSemicolonKeyword_1_2_3; }

		//"text-alt" "=" text_alt=STRING ";"
		public Group getGroup_1_3() { return cGroup_1_3; }

		//"text-alt"
		public Keyword getTextAltKeyword_1_3_0() { return cTextAltKeyword_1_3_0; }

		//"="
		public Keyword getEqualsSignKeyword_1_3_1() { return cEqualsSignKeyword_1_3_1; }

		//text_alt=STRING
		public Assignment getText_altAssignment_1_3_2() { return cText_altAssignment_1_3_2; }

		//STRING
		public RuleCall getText_altSTRINGTerminalRuleCall_1_3_2_0() { return cText_altSTRINGTerminalRuleCall_1_3_2_0; }

		//";"
		public Keyword getSemicolonKeyword_1_3_3() { return cSemicolonKeyword_1_3_3; }

		//"address" "=" address=STRING ";"
		public Group getGroup_1_4() { return cGroup_1_4; }

		//"address"
		public Keyword getAddressKeyword_1_4_0() { return cAddressKeyword_1_4_0; }

		//"="
		public Keyword getEqualsSignKeyword_1_4_1() { return cEqualsSignKeyword_1_4_1; }

		//address=STRING
		public Assignment getAddressAssignment_1_4_2() { return cAddressAssignment_1_4_2; }

		//STRING
		public RuleCall getAddressSTRINGTerminalRuleCall_1_4_2_0() { return cAddressSTRINGTerminalRuleCall_1_4_2_0; }

		//";"
		public Keyword getSemicolonKeyword_1_4_3() { return cSemicolonKeyword_1_4_3; }

		//"}"
		public Keyword getRightCurlyBracketKeyword_2() { return cRightCurlyBracketKeyword_2; }
	}
	
	
	public class TypeElements extends AbstractEnumRuleElementFinder {
		private final EnumRule rule = (EnumRule) GrammarUtil.findRuleForName(getGrammar(), "Type");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final EnumLiteralDeclaration cDropdownEnumLiteralDeclaration_0 = (EnumLiteralDeclaration)cAlternatives.eContents().get(0);
		private final Keyword cDropdownDropdownKeyword_0_0 = (Keyword)cDropdownEnumLiteralDeclaration_0.eContents().get(0);
		private final EnumLiteralDeclaration cFlyoutEnumLiteralDeclaration_1 = (EnumLiteralDeclaration)cAlternatives.eContents().get(1);
		private final Keyword cFlyoutFlyoutKeyword_1_0 = (Keyword)cFlyoutEnumLiteralDeclaration_1.eContents().get(0);
		private final EnumLiteralDeclaration cAccordionEnumLiteralDeclaration_2 = (EnumLiteralDeclaration)cAlternatives.eContents().get(2);
		private final Keyword cAccordionAccordionKeyword_2_0 = (Keyword)cAccordionEnumLiteralDeclaration_2.eContents().get(0);
		
		/// *Feature:
		//  name = ID '=' type = ID ';'
		//;
		// * / enum Type:
		//	dropdown | flyout | accordion;
		public EnumRule getRule() { return rule; }

		//dropdown | flyout | accordion
		public Alternatives getAlternatives() { return cAlternatives; }

		//dropdown
		public EnumLiteralDeclaration getDropdownEnumLiteralDeclaration_0() { return cDropdownEnumLiteralDeclaration_0; }

		//"dropdown"
		public Keyword getDropdownDropdownKeyword_0_0() { return cDropdownDropdownKeyword_0_0; }

		//flyout
		public EnumLiteralDeclaration getFlyoutEnumLiteralDeclaration_1() { return cFlyoutEnumLiteralDeclaration_1; }

		//"flyout"
		public Keyword getFlyoutFlyoutKeyword_1_0() { return cFlyoutFlyoutKeyword_1_0; }

		//accordion
		public EnumLiteralDeclaration getAccordionEnumLiteralDeclaration_2() { return cAccordionEnumLiteralDeclaration_2; }

		//"accordion"
		public Keyword getAccordionAccordionKeyword_2_0() { return cAccordionAccordionKeyword_2_0; }
	}

	public class StyleElements extends AbstractEnumRuleElementFinder {
		private final EnumRule rule = (EnumRule) GrammarUtil.findRuleForName(getGrammar(), "Style");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final EnumLiteralDeclaration cSimpleEnumLiteralDeclaration_0 = (EnumLiteralDeclaration)cAlternatives.eContents().get(0);
		private final Keyword cSimpleSimpleKeyword_0_0 = (Keyword)cSimpleEnumLiteralDeclaration_0.eContents().get(0);
		private final EnumLiteralDeclaration cComplexEnumLiteralDeclaration_1 = (EnumLiteralDeclaration)cAlternatives.eContents().get(1);
		private final Keyword cComplexComplexKeyword_1_0 = (Keyword)cComplexEnumLiteralDeclaration_1.eContents().get(0);
		
		//enum Style:
		//	simple | complex;
		public EnumRule getRule() { return rule; }

		//simple | complex
		public Alternatives getAlternatives() { return cAlternatives; }

		//simple
		public EnumLiteralDeclaration getSimpleEnumLiteralDeclaration_0() { return cSimpleEnumLiteralDeclaration_0; }

		//"simple"
		public Keyword getSimpleSimpleKeyword_0_0() { return cSimpleSimpleKeyword_0_0; }

		//complex
		public EnumLiteralDeclaration getComplexEnumLiteralDeclaration_1() { return cComplexEnumLiteralDeclaration_1; }

		//"complex"
		public Keyword getComplexComplexKeyword_1_0() { return cComplexComplexKeyword_1_0; }
	}

	public class PositionElements extends AbstractEnumRuleElementFinder {
		private final EnumRule rule = (EnumRule) GrammarUtil.findRuleForName(getGrammar(), "Position");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final EnumLiteralDeclaration cCenterEnumLiteralDeclaration_0 = (EnumLiteralDeclaration)cAlternatives.eContents().get(0);
		private final Keyword cCenterCenterKeyword_0_0 = (Keyword)cCenterEnumLiteralDeclaration_0.eContents().get(0);
		private final EnumLiteralDeclaration cLeftEnumLiteralDeclaration_1 = (EnumLiteralDeclaration)cAlternatives.eContents().get(1);
		private final Keyword cLeftLeftKeyword_1_0 = (Keyword)cLeftEnumLiteralDeclaration_1.eContents().get(0);
		private final EnumLiteralDeclaration cRightEnumLiteralDeclaration_2 = (EnumLiteralDeclaration)cAlternatives.eContents().get(2);
		private final Keyword cRightRightKeyword_2_0 = (Keyword)cRightEnumLiteralDeclaration_2.eContents().get(0);
		
		//enum Position:
		//	center | left | right;
		public EnumRule getRule() { return rule; }

		//center | left | right
		public Alternatives getAlternatives() { return cAlternatives; }

		//center
		public EnumLiteralDeclaration getCenterEnumLiteralDeclaration_0() { return cCenterEnumLiteralDeclaration_0; }

		//"center"
		public Keyword getCenterCenterKeyword_0_0() { return cCenterCenterKeyword_0_0; }

		//left
		public EnumLiteralDeclaration getLeftEnumLiteralDeclaration_1() { return cLeftEnumLiteralDeclaration_1; }

		//"left"
		public Keyword getLeftLeftKeyword_1_0() { return cLeftLeftKeyword_1_0; }

		//right
		public EnumLiteralDeclaration getRightEnumLiteralDeclaration_2() { return cRightEnumLiteralDeclaration_2; }

		//"right"
		public Keyword getRightRightKeyword_2_0() { return cRightRightKeyword_2_0; }
	}

	public class DirectionElements extends AbstractEnumRuleElementFinder {
		private final EnumRule rule = (EnumRule) GrammarUtil.findRuleForName(getGrammar(), "Direction");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final EnumLiteralDeclaration cLtrEnumLiteralDeclaration_0 = (EnumLiteralDeclaration)cAlternatives.eContents().get(0);
		private final Keyword cLtrLtrKeyword_0_0 = (Keyword)cLtrEnumLiteralDeclaration_0.eContents().get(0);
		private final EnumLiteralDeclaration cRltEnumLiteralDeclaration_1 = (EnumLiteralDeclaration)cAlternatives.eContents().get(1);
		private final Keyword cRltRltKeyword_1_0 = (Keyword)cRltEnumLiteralDeclaration_1.eContents().get(0);
		private final EnumLiteralDeclaration cAutoEnumLiteralDeclaration_2 = (EnumLiteralDeclaration)cAlternatives.eContents().get(2);
		private final Keyword cAutoAutoKeyword_2_0 = (Keyword)cAutoEnumLiteralDeclaration_2.eContents().get(0);
		
		//enum Direction:
		//	ltr | rlt | auto;
		public EnumRule getRule() { return rule; }

		//ltr | rlt | auto
		public Alternatives getAlternatives() { return cAlternatives; }

		//ltr
		public EnumLiteralDeclaration getLtrEnumLiteralDeclaration_0() { return cLtrEnumLiteralDeclaration_0; }

		//"ltr"
		public Keyword getLtrLtrKeyword_0_0() { return cLtrLtrKeyword_0_0; }

		//rlt
		public EnumLiteralDeclaration getRltEnumLiteralDeclaration_1() { return cRltEnumLiteralDeclaration_1; }

		//"rlt"
		public Keyword getRltRltKeyword_1_0() { return cRltRltKeyword_1_0; }

		//auto
		public EnumLiteralDeclaration getAutoEnumLiteralDeclaration_2() { return cAutoEnumLiteralDeclaration_2; }

		//"auto"
		public Keyword getAutoAutoKeyword_2_0() { return cAutoAutoKeyword_2_0; }
	}

	public class TargetElements extends AbstractEnumRuleElementFinder {
		private final EnumRule rule = (EnumRule) GrammarUtil.findRuleForName(getGrammar(), "Target");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final EnumLiteralDeclaration c_selfEnumLiteralDeclaration_0 = (EnumLiteralDeclaration)cAlternatives.eContents().get(0);
		private final Keyword c_self_selfKeyword_0_0 = (Keyword)c_selfEnumLiteralDeclaration_0.eContents().get(0);
		private final EnumLiteralDeclaration c_blankEnumLiteralDeclaration_1 = (EnumLiteralDeclaration)cAlternatives.eContents().get(1);
		private final Keyword c_blank_blankKeyword_1_0 = (Keyword)c_blankEnumLiteralDeclaration_1.eContents().get(0);
		private final EnumLiteralDeclaration c_parentEnumLiteralDeclaration_2 = (EnumLiteralDeclaration)cAlternatives.eContents().get(2);
		private final Keyword c_parent_parentKeyword_2_0 = (Keyword)c_parentEnumLiteralDeclaration_2.eContents().get(0);
		private final EnumLiteralDeclaration c_topEnumLiteralDeclaration_3 = (EnumLiteralDeclaration)cAlternatives.eContents().get(3);
		private final Keyword c_top_topKeyword_3_0 = (Keyword)c_topEnumLiteralDeclaration_3.eContents().get(0);
		
		//enum Target:
		//	_self | _blank | _parent | _top;
		public EnumRule getRule() { return rule; }

		//_self | _blank | _parent | _top
		public Alternatives getAlternatives() { return cAlternatives; }

		//_self
		public EnumLiteralDeclaration get_selfEnumLiteralDeclaration_0() { return c_selfEnumLiteralDeclaration_0; }

		//"_self"
		public Keyword get_self_selfKeyword_0_0() { return c_self_selfKeyword_0_0; }

		//_blank
		public EnumLiteralDeclaration get_blankEnumLiteralDeclaration_1() { return c_blankEnumLiteralDeclaration_1; }

		//"_blank"
		public Keyword get_blank_blankKeyword_1_0() { return c_blank_blankKeyword_1_0; }

		//_parent
		public EnumLiteralDeclaration get_parentEnumLiteralDeclaration_2() { return c_parentEnumLiteralDeclaration_2; }

		//"_parent"
		public Keyword get_parent_parentKeyword_2_0() { return c_parent_parentKeyword_2_0; }

		//_top
		public EnumLiteralDeclaration get_topEnumLiteralDeclaration_3() { return c_topEnumLiteralDeclaration_3; }

		//"_top"
		public Keyword get_top_topKeyword_3_0() { return c_top_topKeyword_3_0; }
	}
	
	private final MenuElements pMenu;
	private final ConfigurationsElements pConfigurations;
	private final ConfigElements pConfig;
	private final ItemElements pItem;
	private final SubMenuElements pSubMenu;
	private final IconElements pIcon;
	private final TypeElements unknownRuleType;
	private final StyleElements unknownRuleStyle;
	private final PositionElements unknownRulePosition;
	private final DirectionElements unknownRuleDirection;
	private final TargetElements unknownRuleTarget;
	private final TerminalRule tFEATURE;
	private final TerminalRule tCOLOR;
	private final TerminalRule tHEX;
	
	private final Grammar grammar;

	private final TerminalsGrammarAccess gaTerminals;

	@Inject
	public AMenuGrammarAccess(GrammarProvider grammarProvider,
		TerminalsGrammarAccess gaTerminals) {
		this.grammar = internalFindGrammar(grammarProvider);
		this.gaTerminals = gaTerminals;
		this.pMenu = new MenuElements();
		this.pConfigurations = new ConfigurationsElements();
		this.pConfig = new ConfigElements();
		this.pItem = new ItemElements();
		this.pSubMenu = new SubMenuElements();
		this.pIcon = new IconElements();
		this.unknownRuleType = new TypeElements();
		this.unknownRuleStyle = new StyleElements();
		this.unknownRulePosition = new PositionElements();
		this.unknownRuleDirection = new DirectionElements();
		this.unknownRuleTarget = new TargetElements();
		this.tFEATURE = (TerminalRule) GrammarUtil.findRuleForName(getGrammar(), "FEATURE");
		this.tCOLOR = (TerminalRule) GrammarUtil.findRuleForName(getGrammar(), "COLOR");
		this.tHEX = (TerminalRule) GrammarUtil.findRuleForName(getGrammar(), "HEX");
	}
	
	protected Grammar internalFindGrammar(GrammarProvider grammarProvider) {
		Grammar grammar = grammarProvider.getGrammar(this);
		while (grammar != null) {
			if ("br.usp.icmc.amenu.AMenu".equals(grammar.getName())) {
				return grammar;
			}
			List<Grammar> grammars = grammar.getUsedGrammars();
			if (!grammars.isEmpty()) {
				grammar = grammars.iterator().next();
			} else {
				return null;
			}
		}
		return grammar;
	}
	
	
	public Grammar getGrammar() {
		return grammar;
	}
	

	public TerminalsGrammarAccess getTerminalsGrammarAccess() {
		return gaTerminals;
	}

	
	//Menu:
	//	("id" "=" name=ID ";")? & "type" "=" type=Type ";" & ("style" "=" style=Style ";")? & ("position" "="
	//	position=Position ";")? & ("class" "=" decorator=STRING ";")? & ("config" "=" "[" configuration=Configurations "]"
	//	";")? & "items" "=" "[" items+=Item ("," items+=Item)* "]" ";";
	public MenuElements getMenuAccess() {
		return pMenu;
	}
	
	public ParserRule getMenuRule() {
		return getMenuAccess().getRule();
	}

	//Configurations:
	//	("top" config_top+=Config | "children" config_children+=Config) ("," "top" config_top+=Config | "," "children"
	//	config_children+=Config)*;
	public ConfigurationsElements getConfigurationsAccess() {
		return pConfigurations;
	}
	
	public ParserRule getConfigurationsRule() {
		return getConfigurationsAccess().getRule();
	}

	//Config:
	//	"-" feature=FEATURE "=" color=COLOR;
	public ConfigElements getConfigAccess() {
		return pConfig;
	}
	
	public ParserRule getConfigRule() {
		return getConfigAccess().getRule();
	}

	//Item:
	//	"{" (("id" "=" name=ID ";")? & ("class" "=" decorator=STRING ";")? & ("action" "=" action=STRING ";")? & "label" "="
	//	label=STRING ";" & ("title" "=" title=STRING ";")? & ("dir" "=" direction=Direction ";")? & ("target" "="
	//	target=Target ";")? & ("icon" "=" icon=Icon ";")? & ("submenu" "=" submenu=SubMenu ";")?) "}";
	public ItemElements getItemAccess() {
		return pItem;
	}
	
	public ParserRule getItemRule() {
		return getItemAccess().getRule();
	}

	//SubMenu:
	//	"{" (("class" "=" decorator=STRING ";")? / * ( 'id = ' name=ID ';' )? * / & "items" "=" "[" (items+=Item (","
	//	items+=Item)*) "]" ";") "}";
	public SubMenuElements getSubMenuAccess() {
		return pSubMenu;
	}
	
	public ParserRule getSubMenuRule() {
		return getSubMenuAccess().getRule();
	}

	//Icon:
	//	"{" (("id" "=" name=ID ";")? & ("position" "=" position=Position ";")? & ("class" "=" decorator=STRING ";")? &
	//	"text-alt" "=" text_alt=STRING ";" & "address" "=" address=STRING ";") / * & ( features += Feature )* * / "}";
	public IconElements getIconAccess() {
		return pIcon;
	}
	
	public ParserRule getIconRule() {
		return getIconAccess().getRule();
	}

	/// *Feature:
	//  name = ID '=' type = ID ';'
	//;
	// * / enum Type:
	//	dropdown | flyout | accordion;
	public TypeElements getTypeAccess() {
		return unknownRuleType;
	}
	
	public EnumRule getTypeRule() {
		return getTypeAccess().getRule();
	}

	//enum Style:
	//	simple | complex;
	public StyleElements getStyleAccess() {
		return unknownRuleStyle;
	}
	
	public EnumRule getStyleRule() {
		return getStyleAccess().getRule();
	}

	//enum Position:
	//	center | left | right;
	public PositionElements getPositionAccess() {
		return unknownRulePosition;
	}
	
	public EnumRule getPositionRule() {
		return getPositionAccess().getRule();
	}

	//enum Direction:
	//	ltr | rlt | auto;
	public DirectionElements getDirectionAccess() {
		return unknownRuleDirection;
	}
	
	public EnumRule getDirectionRule() {
		return getDirectionAccess().getRule();
	}

	//enum Target:
	//	_self | _blank | _parent | _top;
	public TargetElements getTargetAccess() {
		return unknownRuleTarget;
	}
	
	public EnumRule getTargetRule() {
		return getTargetAccess().getRule();
	}

	//terminal FEATURE:
	//	"background" | "background-hover" | "color" | "color-hover" | "border";
	public TerminalRule getFEATURERule() {
		return tFEATURE;
	} 

	//terminal COLOR:
	//	"#" HEX HEX HEX (HEX HEX HEX)?;
	public TerminalRule getCOLORRule() {
		return tCOLOR;
	} 

	//terminal HEX:
	//	"a".."h" | "A".."H" | "0".."9";
	public TerminalRule getHEXRule() {
		return tHEX;
	} 

	//terminal ID:
	//	"^"? ("a".."z" | "A".."Z" | "_") ("a".."z" | "A".."Z" | "_" | "0".."9")*;
	public TerminalRule getIDRule() {
		return gaTerminals.getIDRule();
	} 

	//terminal INT returns ecore::EInt:
	//	"0".."9"+;
	public TerminalRule getINTRule() {
		return gaTerminals.getINTRule();
	} 

	//terminal STRING:
	//	"\"" ("\\" . / * 'b'|'t'|'n'|'f'|'r'|'u'|'"'|"'"|'\\' * / | !("\\" | "\""))* "\"" | "\'" ("\\" .
	//	/ * 'b'|'t'|'n'|'f'|'r'|'u'|'"'|"'"|'\\' * / | !("\\" | "\'"))* "\'";
	public TerminalRule getSTRINGRule() {
		return gaTerminals.getSTRINGRule();
	} 

	//terminal ML_COMMENT:
	//	"/ *"->"* /";
	public TerminalRule getML_COMMENTRule() {
		return gaTerminals.getML_COMMENTRule();
	} 

	//terminal SL_COMMENT:
	//	"//" !("\n" | "\r")* ("\r"? "\n")?;
	public TerminalRule getSL_COMMENTRule() {
		return gaTerminals.getSL_COMMENTRule();
	} 

	//terminal WS:
	//	(" " | "\t" | "\r" | "\n")+;
	public TerminalRule getWSRule() {
		return gaTerminals.getWSRule();
	} 

	//terminal ANY_OTHER:
	//	.;
	public TerminalRule getANY_OTHERRule() {
		return gaTerminals.getANY_OTHERRule();
	} 
}
