/*
 * generated by Xtext
 */
package br.usp.icmc.amenu.ui;

import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;

import com.google.inject.Injector;

import br.usp.icmc.amenu.ui.internal.AMenuActivator;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class AMenuExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return AMenuActivator.getInstance().getBundle();
	}
	
	@Override
	protected Injector getInjector() {
		return AMenuActivator.getInstance().getInjector(AMenuActivator.BR_USP_ICMC_AMENU_AMENU);
	}
	
}
